FROM registry.access.redhat.com/ubi9/ubi-minimal:9.2
LABEL maintainer=David\ Rabkin\ <david@rabkin.co.il>
ENV \
	USER=shellbase
COPY LICENSE /licenses/LICENSE
WORKDIR /bin
COPY --from=ghcr.io/rdavid/goredoer:0.9.20230504 /go/goredo .
RUN \
	microdnf update --assumeyes --disableplugin=subscription-manager \
	&& rm --force --recursive /var/cache/yum \
	&& microdnf install --assumeyes --disableplugin=subscription-manager \
		bash-5.1.8 \
		findutils-4.8.0 \
		shadow-utils-4.9 \
	&& microdnf clean all --disableplugin=subscription-manager \
	&& useradd --create-home "$USER" \
	&& goredo -symlinks
USER "$USER"
WORKDIR /home/"$USER"
COPY \
	--chown="$USER":"$USER" \
	. .
CMD \
	[ "redo", "-j=10", "-x", "test" ]
