# SPDX-FileCopyrightText: 2026 David Rabkin
# SPDX-License-Identifier: 0BSD
FROM ghcr.io/rdavid/goredoer:0.9.20260707 as goredoer
FROM registry.access.redhat.com/ubi10/ubi-minimal:10.2-1784094212
LABEL maintainer=David\ Rabkin\ <david@rabkin.co.il>
ENV \
	TZ=Asia/Jerusalem \
	USER=shellbase
COPY LICENSES/* /licenses/
WORKDIR /bin
COPY --from=goredoer /goredo .
RUN \
	microdnf update --assumeyes --disableplugin=subscription-manager \
	&& rm --force --recursive /var/cache/yum \
	&& microdnf install --assumeyes --disableplugin=subscription-manager \
		bash-5.2.26 \
		diffutils-3.10 \
		findutils-4.10.0 \
		perl-Digest-SHA-6.04 \
		procps-ng-4.0.4 \
		tzdata-2026b \
		util-linux-2.40.2 \
	&& microdnf clean all --disableplugin=subscription-manager \
	&& useradd --create-home "$USER" \
	&& goredo -symlinks
USER "$USER"
WORKDIR /home/"$USER"
COPY \
	--chown="$USER":"$USER" \
	. .
ENTRYPOINT [ "redo", "-j=10" ]
