# SPDX-FileCopyrightText: 2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
policies:
  - type: commit
    spec:
      conventional:
        scopes:
          - ".*"
        types:
          - build
          - chore
          - ci
          - docs
          - feat
          - fix
          - perf
          - refactor
          - revert
          - style
          - test
      header:
        case: lower
        imperative: true
        invalidLastCharacters: .
        length: 89
      spellcheck:
        locale: US
