// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-hoc: https://hitsofcode.com/github/rdavid/shellbase?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/shellbase?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-releases: https://img.shields.io/github/v/release/rdavid/shellbase?color=blue&label=%20&logo=semver&logoColor=white&style=flat
:img-test-bsd: https://github.com/rdavid/shellbase/actions/workflows/test-bsd.yml/badge.svg
:img-test-lnx: https://github.com/rdavid/shellbase/actions/workflows/test-lnx.yml/badge.svg
:img-test-mac: https://github.com/rdavid/shellbase/actions/workflows/test-mac.yml/badge.svg
:url-actionlint: https://github.com/rhysd/actionlint
:url-base: https://github.com/rdavid/shellbase/blob/master/lib/base.sh
:url-checkmake: https://github.com/mrtazz/checkmake
:url-cv: http://cv.rabkin.co.il
:url-dotfiles: https://github.com/rdavid/dotfiles
:url-gento: https://github.com/rdavid/gento
:url-goredo: http://www.goredo.stargrave.org/INSTALL.html
:url-goredoer: https://github.com/rdavid/goredoer
:url-hadolint: https://github.com/hadolint/hadolint
:url-hoc: https://hitsofcode.com/view/github/rdavid/shellbase?branch=master
:url-license: https://github.com/rdavid/shellbase/blob/master/LICENSES/0BSD.txt
:url-pulse: https://github.com/rdavid/pulse
:url-redo: http://cr.yp.to/redo.html
:url-releases: https://github.com/rdavid/shellbase/releases
:url-reuse: https://github.com/fsfe/reuse-action
:url-sh0: https://mywiki.wooledge.org/BashPitfalls
:url-sh1: http://www.etalabs.net/sh_tricks.html
:url-sh2: https://mywiki.wooledge.org/SignalTrap
:url-sh3: https://www.grymoire.com/Unix/Sh.html
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shfmt: https://github.com/mvdan/sh
:url-test-bsd: https://github.com/rdavid/shellbase/actions/workflows/test-bsd.yml
:url-test-lnx: https://github.com/rdavid/shellbase/actions/workflows/test-lnx.yml
:url-test-mac: https://github.com/rdavid/shellbase/actions/workflows/test-mac.yml
:url-toolbox: https://github.com/rdavid/toolbox
:url-typos: https://github.com/crate-ci/typos
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint
:url-zizmor: https://github.com/zizmorcore/zizmor

= Shellbase

// The width is set to 79 characters, and the height is 8 lines. An ASCII art
// generator is used with the specific font Georgia 11 by Richard Sabey
// <cryptic_fan@hotmail.com> 9.2003:
//  http://patorjk.com/software/taag/#p=display&f=Georgia11&t=shellbase
[,sh]
----
             ,,                 ,,    ,,  ,,                                  
           `7MM               `7MM  `7MM *MM                                  
             MM                 MM    MM  MM                                  
    ,pP"Ybd  MMpMMMb.  .gP"Ya   MM    MM  MM,dMMb.   ,6"Yb.  ,pP"Ybd  .gP"Ya  
    8I   `"  MM    MM ,M'   Yb  MM    MM  MM    `Mb 8)   MM  8I   `" ,M'   Yb 
    `YMMMa.  MM    MM 8M""""""  MM    MM  MM     M8  ,pm9MM  `YMMMa. 8M"""""" 
    L.   I8  MM    MM YM.    ,  MM    MM  MM.   ,M9 8M   MM  L.   I8 YM.    , 
    M9mmmP'.JMML  JMML.`Mbmmd'.JMML..JMML.P^YbmdP'  `Moo9^Yo.M9mmmP'  `Mbmmd' 
----

image:{img-test-bsd}[text bsd,link={url-test-bsd}]
image:{img-test-lnx}[text lnx,link={url-test-lnx}]
image:{img-test-mac}[test mac,link={url-test-mac}]
image:{img-hoc}[hits of code,link={url-hoc}]
image:{img-releases}[release,link={url-releases}]
image:{img-license}[license,link={url-license}]

toc::[]

== About

The `shellbase` framework serves as a foundation for Unix shell scripts.
It follows POSIX, the Portable Operating System Interface standard, and runs
on any Unix-like system.
The framework provides logging, validation helpers, signal handling, garbage
collection, and support for concurrent instances.

`shellbase` defines global variables and functions.
Clients may call any function without the `base_` prefix.
The public functions are, in alphabetical order:
{url-base}#L59[`aud_only`],
{url-base}#L98[`beroot`],
{url-base}#L105[`beuser`],
{url-base}#L119[`bomb`],
{url-base}#L125[`cheat`],
{url-base}#L132[`chrono_get`],
{url-base}#L172[`chrono_sta`],
{url-base}#L183[`chrono_sto`],
{url-base}#L200[`cmd_exists`],
{url-base}#L237[`cmd_run`],
{url-base}#L271[`cmd_runif`],
{url-base}#L280[`cya`],
{url-base}#L290[`die`],
{url-base}#L298[`dng2jpg`],
{url-base}#L307[`echo`],
{url-base}#L327[`ellipsize`],
{url-base}#L360[`file_exists`],
{url-base}#L376[`gitfix`],
{url-base}#L392[`gitlog`],
{url-base}#L418[`grbt`],
{url-base}#L435[`handle_pipefails`],
{url-base}#L442[`heic2jpg`],
{url-base}#L455[`inside`],
{url-base}#L462[`isempty`],
{url-base}#L486[`isfunc`],
{url-base}#L499[`isnumber`],
{url-base}#L507[`isreadable`],
{url-base}#L516[`isroot`],
{url-base}#L529[`issolid`],
{url-base}#L563[`iswritable`],
{url-base}#L576[`log`],
{url-base}#L585[`loge`],
{url-base}#L593[`logw`],
{url-base}#L602[`map_del`],
{url-base}#L622[`map_get`],
{url-base}#L644[`map_put`],
{url-base}#L661[`nmea2gpx`],
{url-base}#L675[`pdf2jpg`],
{url-base}#L680[`pdf2png`],
{url-base}#L702[`prettytable`],
{url-base}#L723[`prettyuptime`],
{url-base}#L746[`realdir`],
{url-base}#L755[`realpath`],
{url-base}#L766[`retry`],
{url-base}#L803[`rev`],
{url-base}#L821[`semver`],
{url-base}#L850[`should_continue`],
{url-base}#L908[`timestamp`],
{url-base}#L928[`tolog`],
{url-base}#L934[`tologe`],
{url-base}#L941[`tolower`],
{url-base}#L959[`totsout`],
{url-base}#L965[`tsout`],
{url-base}#L974[`url_exists`],
{url-base}#L1003[`user_exists`],
{url-base}#L1022[`validate_cmd`],
{url-base}#L1029[`validate_var`],
{url-base}#L1047[`var_exists`],
{url-base}#L1087[`ver_ge`],
{url-base}#L1098[`vid2aud`],
{url-base}#L1119[`ytda`].

Global variables carry the `BASE_` prefix.
Clients may use them and should place temporary files under `$BASE_WIP`.
Functions with the `base_` prefix stay internal.
Clients shouldn't call them.

See
{url-dotfiles}[`dotfiles`],
{url-gento}[`gento`],
{url-pulse}[`pulse`], and
{url-toolbox}[`toolbox`]
for example projects built on the framework.

== Install

The framework ships as a single non-executable POSIX shell script,
{url-base}[`base.sh`].
Install the file from the repository:

[,sh]
----
git clone https://github.com/rdavid/shellbase.git &&
  ./shellbase/app/install
----

Or install the file from a release.
Some operating systems demand administrative rights to write to
`/usr/local/bin`.
Prefix `tar` with `sudo` or `doas` when needed:

[,sh]
----
REL=0.9.20260707
SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v$REL.tar.gz
curl --location --silent $SRC |
  tar \
    --directory /usr/local/bin \
    --extract \
    --gzip \
    --strip-components=2 \
    shellbase-$REL/lib/base.sh
----

== Using

Verify `/usr/local/bin` appears in your `PATH`.
Then source the framework from your script:

[,sh]
----
#!/bin/sh
# File not following:
#  shellcheck disable=SC1091
. base.sh
log I\'m using the shellbase.
----

The framework provides three loggers:
{url-base}#L576[`log`] for information,
{url-base}#L585[`loge`] for errors, and
{url-base}#L593[`logw`] for warnings.
Each logger prints to standard error.
In non-interactive mode, each also appends the message to the log file under
a single lowercase level tag: `i` for information, `e` for errors, and `w`
for warnings.

Try `shellbase` without installation:

[,sh]
----
#!/bin/sh
REL=0.9.20260707
SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v$REL.tar.gz
eval "$(
  curl --location --silent $SRC |
    tar \
      --extract \
      --gzip \
      --to-stdout \
      shellbase-$REL/lib/base.sh
)"
log I\'m using the shellbase.
----

{url-base}#L702[`prettytable`] example:

[,sh]
----
. base.sh
{
  printf 'ID\tNAME\tTITLE\n'
  printf '123456789\tJohn Foo\tDirector\n'
  printf '12\tMike Bar\tEngineer\n'
} | prettytable
----

Output:

[,sh]
----
+-----------+----------+----------+
|ID         |NAME      |TITLE     |
+-----------+----------+----------+
|123456789  |John Foo  |Director  |
|12         |Mike Bar  |Engineer  |
+-----------+----------+----------+
----

== Test

The project uses Daniel J. Bernstein's build system, {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.
`redo lint` applies the following linters to the source files:
{url-actionlint}[`actionlint`],
{url-checkmake}[`checkmake`],
{url-hadolint}[`hadolint`],
{url-reuse}[`reuse`],
{url-shellcheck}[`shellcheck`],
{url-shfmt}[`shfmt`],
{url-typos}[`typos`],
{url-vale}[`vale`],
{url-yamllint}[`yamllint`],
{url-zizmor}[`zizmor`].
`redo test` runs the unit tests against each installed shell.
`redo test-container` repeats the tests inside the supported container
images.
The project uses {url-cv}[David Rabkin]'s {url-goredoer}[`goredoer`] to build
{url-goredo}[`goredo`].

== Links

- {url-sh0}[Bash Pitfalls]
- {url-sh1}[Rich’s sh (POSIX shell) tricks]
- {url-sh2}[Sending and Trapping Signals]
- {url-sh3}[Sh - the POSIX Shell]

== License

`shellbase` belongs to {url-cv}[David Rabkin] and uses a
{url-license}[Zero-Clause BSD license].
