// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-hoc: https://hitsofcode.com/github/rdavid/shellbase?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/shellbase?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-releases: https://img.shields.io/github/v/release/rdavid/shellbase?color=blue&label=%20&logo=semver&logoColor=white&style=flat
:img-test-bsd: https://github.com/rdavid/shellbase/actions/workflows/test-bsd.yml/badge.svg
:img-test-lnx: https://github.com/rdavid/shellbase/actions/workflows/test-lnx.yml/badge.svg
:img-test-mac: https://github.com/rdavid/shellbase/actions/workflows/test-mac.yml/badge.svg
:url-actionlint: https://github.com/rhysd/actionlint
:url-base: https://github.com/rdavid/shellbase/blob/master/lib/base.sh
:url-checkmake: https://github.com/mrtazz/checkmake
:url-cv: http://cv.rabkin.co.il
:url-dotfiles: https://github.com/rdavid/dotfiles
:url-gento: https://github.com/rdavid/gento
:url-goredo: http://www.goredo.stargrave.org/INSTALL.html
:url-goredoer: https://github.com/rdavid/goredoer
:url-hadolint: https://github.com/hadolint/hadolint
:url-hoc: https://hitsofcode.com/view/github/rdavid/shellbase?branch=master
:url-license: https://github.com/rdavid/shellbase/blob/master/LICENSES/0BSD.txt
:url-pulse: https://github.com/rdavid/pulse
:url-redo: http://cr.yp.to/redo.html
:url-releases: https://github.com/rdavid/shellbase/releases
:url-reuse: https://github.com/fsfe/reuse-action
:url-sh0: https://mywiki.wooledge.org/BashPitfalls
:url-sh1: http://www.etalabs.net/sh_tricks.html
:url-sh2: https://mywiki.wooledge.org/SignalTrap
:url-sh3: https://www.grymoire.com/Unix/Sh.html
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shfmt: https://github.com/mvdan/sh
:url-test-bsd: https://github.com/rdavid/shellbase/actions/workflows/test-bsd.yml
:url-test-lnx: https://github.com/rdavid/shellbase/actions/workflows/test-lnx.yml
:url-test-mac: https://github.com/rdavid/shellbase/actions/workflows/test-mac.yml
:url-toolbox: https://github.com/rdavid/toolbox
:url-typos: https://github.com/crate-ci/typos
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint
:url-zizmor: https://github.com/zizmorcore/zizmor

= Shellbase

// The width is set to 79 characters, and the height is 8 lines. An ASCII art
// generator is used with the specific font Georgia 11 by Richard Sabey
// <cryptic_fan@hotmail.com> 9.2003:
//  http://patorjk.com/software/taag/#p=display&f=Georgia11&t=shellbase
[,sh]
----
             ,,                 ,,    ,,  ,,                                  
           `7MM               `7MM  `7MM *MM                                  
             MM                 MM    MM  MM                                  
    ,pP"Ybd  MMpMMMb.  .gP"Ya   MM    MM  MM,dMMb.   ,6"Yb.  ,pP"Ybd  .gP"Ya  
    8I   `"  MM    MM ,M'   Yb  MM    MM  MM    `Mb 8)   MM  8I   `" ,M'   Yb 
    `YMMMa.  MM    MM 8M""""""  MM    MM  MM     M8  ,pm9MM  `YMMMa. 8M"""""" 
    L.   I8  MM    MM YM.    ,  MM    MM  MM.   ,M9 8M   MM  L.   I8 YM.    , 
    M9mmmP'.JMML  JMML.`Mbmmd'.JMML..JMML.P^YbmdP'  `Moo9^Yo.M9mmmP'  `Mbmmd' 
----

image:{img-test-bsd}[text bsd,link={url-test-bsd}]
image:{img-test-lnx}[text lnx,link={url-test-lnx}]
image:{img-test-mac}[test mac,link={url-test-mac}]
image:{img-hoc}[hits of code,link={url-hoc}]
image:{img-releases}[release,link={url-releases}]
image:{img-license}[license,link={url-license}]

toc::[]

== About

The `shellbase` framework serves as a foundation for Unix shell scripts.
It follows POSIX, the Portable Operating System Interface standard, and runs
across Unix-like systems.
The framework offers essential services, including logging, validation
helpers, signal handling, garbage collection, and support for concurrent
instances.

`shellbase` defines global variables and functions.
Functions without the `base_` prefix are public, and clients may call them.
The public functions are, in alphabetical order:
{url-base}#L57[`aud_only`],
{url-base}#L105[`beroot`],
{url-base}#L110[`beuser`],
{url-base}#L121[`bomb`],
{url-base}#L127[`cheat`],
{url-base}#L134[`chrono_get`],
{url-base}#L174[`chrono_sta`],
{url-base}#L185[`chrono_sto`],
{url-base}#L202[`cmd_exists`],
{url-base}#L239[`cmd_run`],
{url-base}#L277[`cmd_runif`],
{url-base}#L286[`cya`],
{url-base}#L296[`die`],
{url-base}#L304[`dng2jpg`],
{url-base}#L313[`echo`],
{url-base}#L333[`ellipsize`],
{url-base}#L367[`file_exists`],
{url-base}#L376[`gitlog`],
{url-base}#L400[`grbt`],
{url-base}#L412[`handle_pipefails`],
{url-base}#L419[`heic2jpg`],
{url-base}#L432[`inside`],
{url-base}#L439[`isempty`],
{url-base}#L463[`isfunc`],
{url-base}#L476[`isnumber`],
{url-base}#L484[`isreadable`],
{url-base}#L493[`isroot`],
{url-base}#L505[`issolid`],
{url-base}#L539[`iswritable`],
{url-base}#L553[`log`],
{url-base}#L562[`loge`],
{url-base}#L570[`logw`],
{url-base}#L579[`map_del`],
{url-base}#L599[`map_get`],
{url-base}#L621[`map_put`],
{url-base}#L635[`nmea2gpx`],
{url-base}#L651[`pdf2jpg`],
{url-base}#L656[`pdf2png`],
{url-base}#L677[`prettytable`],
{url-base}#L697[`prettyuptime`],
{url-base}#L720[`realdir`],
{url-base}#L729[`realpath`],
{url-base}#L740[`retry`],
{url-base}#L780[`semver`],
{url-base}#L798[`should_continue`],
{url-base}#L856[`timestamp`],
{url-base}#L876[`tolog`],
{url-base}#L882[`tologe`],
{url-base}#L889[`tolower`],
{url-base}#L907[`totsout`],
{url-base}#L913[`tsout`],
{url-base}#L921[`url_exists`],
{url-base}#L945[`user_exists`],
{url-base}#L961[`validate_cmd`],
{url-base}#L968[`validate_var`],
{url-base}#L986[`var_exists`],
{url-base}#L1026[`ver_ge`],
{url-base}#L1034[`vid2aud`],
{url-base}#L1048[`ytda`].

Global variables carry the `BASE_` prefix.
Clients may use them and should place temporary files under `$BASE_WIP`.
Functions with the `base_` prefix stay internal, and clients shouldn't call
them.

See
{url-dotfiles}[`dotfiles`],
{url-gento}[`gento`],
{url-pulse}[`pulse`], and
{url-toolbox}[`toolbox`]
as example projects that use this framework.

== Install

The framework ships as a single non-executable POSIX-compliant shell script,
{url-base}[`base.sh`].
Install the file from the repository:

[,sh]
----
git clone https://github.com/rdavid/shellbase.git &&
  ./shellbase/app/install
----

Alternatively, install the file from a release.
Some operating systems demand administrative rights to write to
`/usr/local/bin`.
Prefix `tar` with `sudo` or `doas` when needed:

[,sh]
----
REL=0.9.20260404
SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v$REL.tar.gz
curl --location --silent $SRC |
  tar \
    --directory /usr/local/bin \
    --extract \
    --gzip \
    --strip-components=2 \
    shellbase-$REL/lib/base.sh
----

== Using

Verify `/usr/local/bin` appears in your `PATH`.
Then source the framework from your script:

[,sh]
----
#!/bin/sh
# File not following:
#  shellcheck disable=SC1091
. base.sh
log I\'m using the shellbase.
----

The framework provides three loggers:
{url-base}#L553[`log`] for information,
{url-base}#L562[`loge`] for errors, and
{url-base}#L570[`logw`] for warnings.
Each prints to standard error and, in non-interactive mode, appends the message
to the log file under a single lowercase level tag: `i` for information, `e` for
errors, and `w` for warnings.

You can try `shellbase` without installation:

[,sh]
----
#!/bin/sh
REL=0.9.20260404
SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v$REL.tar.gz
eval "$(
  curl --location --silent $SRC |
    tar \
      --extract \
      --gzip \
      --to-stdout \
      shellbase-$REL/lib/base.sh
)"
log I\'m using the shellbase.
----

{url-base}#L677[`prettytable`] example:

[,sh]
----
. base.sh
{
  printf 'ID\tNAME\tTITLE\n'
  printf '123456789\tJohn Foo\tDirector\n'
  printf '12\tMike Bar\tEngineer\n'
} | prettytable
----

Output:

[,sh]
----
+-----------+----------+----------+
|ID         |NAME      |TITLE     |
+-----------+----------+----------+
|123456789  |John Foo  |Director  |
|12         |Mike Bar  |Engineer  |
+-----------+----------+----------+
----

== Test

The project uses Daniel J. Bernstein's build system, {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.
`redo lint` applies the following linters to the source files:
{url-actionlint}[`actionlint`],
{url-checkmake}[`checkmake`],
{url-hadolint}[`hadolint`],
{url-reuse}[`reuse`],
{url-shellcheck}[`shellcheck`],
{url-shfmt}[`shfmt`],
{url-typos}[`typos`],
{url-vale}[`vale`],
{url-yamllint}[`yamllint`],
{url-zizmor}[`zizmor`].
`redo test` runs unit tests across installed shells.
`redo test-container` runs the tests across various shells in containers.
The project uses {url-cv}[David Rabkin]'s {url-goredoer}[`goredoer`] to build
{url-goredo}[`goredo`].

== Links

- {url-sh0}[Bash Pitfalls]
- {url-sh1}[Rich’s sh (POSIX shell) tricks]
- {url-sh2}[Sending and Trapping Signals]
- {url-sh3}[Sh - the POSIX Shell]

== License

`shellbase` belongs to {url-cv}[David Rabkin] and uses a
{url-license}[Zero-Clause BSD license].
