// Settings:
:toc: macro
:!toc-title:
// URLs:
:url-base: https://github.com/rdavid/shellbase/blob/master/lib/base.sh
:url-dotfiles: https://github.com/rdavid/dotfiles
:url-cv: http://cv.rabkin.co.il
:url-license: https://github.com/rdavid/shellbase/blob/master/LICENSE
:url-gento: https://github.com/rdavid/gento
:url-goredo: http://www.goredo.cypherpunks.ru/Install.html
:url-goredoer: https://github.com/rdavid/goredoer
:url-redo: http://cr.yp.to/redo.html
:url-toolbox: https://github.com/rdavid/toolbox

= Shellbase

image:https://github.com/rdavid/shellbase/actions/workflows/lint.yml/badge.svg[linters,link=https://github.com/rdavid/shellbase/actions/workflows/lint.yml]
image:https://hitsofcode.com/github/rdavid/shellbase?branch=master&label=hits%20of%20code[hits of code,link=https://hitsofcode.com/view/github/rdavid/shellbase?branch=master]
image:https://img.shields.io/github/downloads/rdavid/shellbase/total?color=blue&labelColor=gray&logo=singlestore&logoColor=lightgray&style=flat[downloads]
image:https://img.shields.io/github/v/release/rdavid/shellbase?color=blue&label=%20&logo=semver&logoColor=white&style=flat[release),link=https://github.com/rdavid/shellbase/releases]
image:https://img.shields.io/github/license/rdavid/shellbase?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat[license,link=https://github.com/rdavid/shellbase/blob/master/LICENSE]

toc::[]

== About

The `shellbase` framework serves as a foundation for Unix shell scripts.
This framework is mostly POSIX-compliant, ensuring compatibility across
Unix-like systems.
It offers a range of essential services, including public functions such as
logger and multiple validations, signal handling, garbage collection, and
support for multiple instances.

The `shellbase` defines global variables and functions.
All functions without `base_` prefix are public and could be used by clients.
The public functions are, in alphabetical order:
{url-base}#L53[`aud_only`],
{url-base}#L70[`beroot`],
{url-base}#L75[`beuser`],
{url-base}#L86[`cheat`],
{url-base}#L92[`cmd_exists`],
{url-base}#L107[`die`],
{url-base}#L114[`echo`],
{url-base}#L132[`file_exists`],
{url-base}#L147[`grbt`],
{url-base}#L157[`heic2jpg`],
{url-base}#L171[`inside`],
{url-base}#L179[`isempty`],
{url-base}#L193[`isfunc`],
{url-base}#L201[`isreadable`],
{url-base}#L217[`issolid`],
{url-base}#L246[`iswritable`],
{url-base}#L271[`log`],
{url-base}#L280[`loge`],
{url-base}#L288[`logw`],
{url-base}#L297[`pdf2jpg`],
{url-base}#L306[`pdf2png`],
{url-base}#L329[`prettytable`],
{url-base}#L354[`prettyuptime`],
{url-base}#L372[`realdir`],
{url-base}#L381[`realpath`],
{url-base}#L393[`semver`],
{url-base}#L410[`timestamp`],
{url-base}#L430[`tolog`],
{url-base}#L436[`tologe`],
{url-base}#L442[`tolower`],
{url-base}#L447[`totsout`],
{url-base}#L453[`tsout`],
{url-base}#L462[`url_exists`],
{url-base}#L487[`user_exists`],
{url-base}#L503[`validate_cmd`],
{url-base}#L510[`validate_var`],
{url-base}#L517[`var_exists`],
{url-base}#L538[`ver_ge`],
{url-base}#L543[`vid2aud`],
{url-base}#L558[`yes_to_continue`],
{url-base}#L612[`ytda`].

Global variables have `BASE_` prefix and clients could use them.
Clients should place all temporarily files under `$BASE_WIP`.
All functions started with `base_` prefix are internal and should not be used
by clients.
All names are in alphabetical order.

See {url-dotfiles}[`dotfiles`], {url-gento}[`gento`] and {url-toolbox}[`toolbox`] as examples.

== Install

The artifact is a single non-executable POSIX-compliant shell script file
{url-base}[`base.sh`].
Install the file from the repository:

[,sh]
----
git clone git@github.com:rdavid/shellbase.git &&
  ./shellbase/app/install
----

Install the file from the released version.
Some operating systems demands administrative rights to install to
`/usr/local/bin`, use `sudo` or `doas` before `tar`:

[,sh]
----
REL=0.9.20230505
SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v$REL.tar.gz
curl --location --silent $SRC |
  tar \
    --directory /usr/local/bin \
    --extract \
    --gzip \
    --strip-components=2 \
    shellbase-$REL/lib/base.sh
----

Verify `/usr/local/bin` is in your `PATH`.
Then your script can use `shellbase`:

[,sh]
----
#!/bin/sh
# shellcheck disable=SC1091 # File not following.
. base.sh
log I\'m using the shellbase.
----

You can try `shellbase` without installation:

[,sh]
----
#!/bin/sh
REL=0.9.20230505
SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v$REL.tar.gz
eval "$(
  curl --location --silent $SRC |
    tar \
      --extract \
      --gzip \
      --to-stdout \
      shellbase-$REL/lib/base.sh
)"
log I\'m using the shellbase.
----

{url-base}#L329[`prettytable`] example:

[,sh]
----
. base.sh
{
  printf 'ID\tNAME\tTITLE\n'
  printf '123456789\tJohn Foo\tDirector\n'
  printf '12\tMike Bar\tEngineer\n'
} | prettytable
----

Output:

[,sh]
----
+-----------+----------+----------+
|ID         |NAME      |TITLE     |
+-----------+----------+----------+
|123456789  |John Foo  |Director  |
|12         |Mike Bar  |Engineer  |
+-----------+----------+----------+
----

== Test

The project uses Daniel J. Bernstein's (aka, djb) build system
{url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.
`redo lint` runs the following linters on the source files:
https://github.com/mrtazz/checkmake[`checkmake`],
https://github.com/hadolint/hadolint[`hadolint`],
https://github.com/koalaman/shellcheck[`shellcheck`],
https://github.com/mvdan/sh[`shfmt`],
https://vale.sh[`vale`],
https://github.com/adrienverge/yamllint[`yamllint`].
`redo test` runs unit tests in installed shells.
`redo test_container` runs the tests in multiple shells in multiple containers.
It uses {url-cv}[David Rabkin]'s {url-goredoer}[`goredoer`] to build
{url-goredo}[`goredo`].

== License

`shellbase` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].
