// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-hoc: https://hitsofcode.com/github/rdavid/shellbase?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/shellbase?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-releases: https://img.shields.io/github/v/release/rdavid/shellbase?color=blue&label=%20&logo=semver&logoColor=white&style=flat
:img-test-bsd: https://github.com/rdavid/shellbase/actions/workflows/test-bsd.yml/badge.svg
:img-test-lnx: https://github.com/rdavid/shellbase/actions/workflows/test-lnx.yml/badge.svg
:img-test-mac: https://github.com/rdavid/shellbase/actions/workflows/test-mac.yml/badge.svg
:url-actionlint: https://github.com/rhysd/actionlint
:url-base: https://github.com/rdavid/shellbase/blob/master/lib/base.sh
:url-checkmake: https://github.com/mrtazz/checkmake
:url-cv: http://cv.rabkin.co.il
:url-dotfiles: https://github.com/rdavid/dotfiles
:url-gento: https://github.com/rdavid/gento
:url-goredo: http://www.goredo.cypherpunks.su/Install.html
:url-goredoer: https://github.com/rdavid/goredoer
:url-hadolint: https://github.com/hadolint/hadolint
:url-hoc: https://hitsofcode.com/view/github/rdavid/shellbase?branch=master
:url-license: https://github.com/rdavid/shellbase/blob/master/LICENSES/0BSD.txt
:url-pulse: https://github.com/rdavid/pulse
:url-redo: http://cr.yp.to/redo.html
:url-releases: https://github.com/rdavid/shellbase/releases
:url-reuse: https://github.com/fsfe/reuse-action
:url-sh0: https://mywiki.wooledge.org/BashPitfalls
:url-sh1: http://www.etalabs.net/sh_tricks.html
:url-sh2: https://mywiki.wooledge.org/SignalTrap
:url-sh3: https://www.grymoire.com/Unix/Sh.html
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shfmt: https://github.com/mvdan/sh
:url-test-bsd: https://github.com/rdavid/shellbase/actions/workflows/test-bsd.yml
:url-test-lnx: https://github.com/rdavid/shellbase/actions/workflows/test-lnx.yml
:url-test-mac: https://github.com/rdavid/shellbase/actions/workflows/test-mac.yml
:url-toolbox: https://github.com/rdavid/toolbox
:url-typos: https://github.com/crate-ci/typos
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint

= Shellbase

[,sh]
----
             ,,                 ,,    ,,  ,,                                  
           `7MM               `7MM  `7MM *MM                                  
             MM                 MM    MM  MM                                  
    ,pP"Ybd  MMpMMMb.  .gP"Ya   MM    MM  MM,dMMb.   ,6"Yb.  ,pP"Ybd  .gP"Ya  
    8I   `"  MM    MM ,M'   Yb  MM    MM  MM    `Mb 8)   MM  8I   `" ,M'   Yb 
    `YMMMa.  MM    MM 8M""""""  MM    MM  MM     M8  ,pm9MM  `YMMMa. 8M"""""" 
    L.   I8  MM    MM YM.    ,  MM    MM  MM.   ,M9 8M   MM  L.   I8 YM.    , 
    M9mmmP'.JMML  JMML.`Mbmmd'.JMML..JMML.P^YbmdP'  `Moo9^Yo.M9mmmP'  `Mbmmd' 
----

image:{img-test-bsd}[text bsd,link={url-test-bsd}]
image:{img-test-lnx}[text lnx,link={url-test-lnx}]
image:{img-test-mac}[test mac,link={url-test-mac}]
image:{img-hoc}[hits of code,link={url-hoc}]
image:{img-releases}[release),link={url-releases}]
image:{img-license}[license,link={url-license}]

toc::[]

== About

The `shellbase` framework serves as a foundation for Unix shell scripts.
This framework is mostly POSIX-compliant,
`Portable Operating System Interface for uniX`, ensuring compatibility across
Unix-like systems.
It offers a range of essential services, including public functions such as
logger and multiple validations, signal handling, garbage collection, and
support for multiple instances.

The `shellbase` defines global variables and functions.
All functions without `base_` prefix are public and could be used by clients.
The public functions are, in alphabetical order:
{url-base}#L53[`aud_only`],
{url-base}#L97[`beroot`],
{url-base}#L102[`beuser`],
{url-base}#L113[`bomb`],
{url-base}#L119[`cheat`],
{url-base}#L130[`cmd_exists`],
{url-base}#L156[`chrono_get`],
{url-base}#L197[`chrono_sta`],
{url-base}#L208[`chrono_sto`],
{url-base}#L218[`cya`],
{url-base}#L228[`die`],
{url-base}#L238[`dng2jpg`],
{url-base}#L244[`echo`],
{url-base}#L266[`ellipsize`],
{url-base}#L284[`file_exists`],
{url-base}#L292[`gitlog`],
{url-base}#L316[`grbt`],
{url-base}#L328[`handle_pipefails`],
{url-base}#L334[`heic2jpg`],
{url-base}#L347[`inside`],
{url-base}#L354[`isempty`],
{url-base}#L378[`isfunc`],
{url-base}#L391[`isnumber`],
{url-base}#L399[`isreadable`],
{url-base}#L408[`isroot`],
{url-base}#L420[`issolid`],
{url-base}#L454[`iswritable`],
{url-base}#L468[`log`],
{url-base}#L477[`loge`],
{url-base}#L485[`logw`],
{url-base}#L494[`map_del`],
{url-base}#L514[`map_get`],
{url-base}#L536[`map_put`],
{url-base}#L548[`pdf2jpg`],
{url-base}#L553[`pdf2png`],
{url-base}#L572[`prettytable`],
{url-base}#L598[`prettyuptime`],
{url-base}#L622[`raw2jpg`],
{url-base}#L629[`realdir`],
{url-base}#L638[`realpath`],
{url-base}#L651[`semver`],
{url-base}#L669[`should_continue`],
{url-base}#L725[`timestamp`],
{url-base}#L745[`tolog`],
{url-base}#L751[`tologe`],
{url-base}#L758[`tolower`],
{url-base}#L776[`totsout`],
{url-base}#L782[`tsout`],
{url-base}#L790[`url_exists`],
{url-base}#L814[`user_exists`],
{url-base}#L830[`validate_cmd`],
{url-base}#L837[`validate_var`],
{url-base}#L844[`var_exists`],
{url-base}#L866[`ver_ge`],
{url-base}#L874[`vid2aud`],
{url-base}#L888[`ytda`].

Global variables have `BASE_` prefix and clients could use them.
Clients should place temporary files under `$BASE_WIP`.
All functions started with `base_` prefix are internal and should not be used
by clients.
The names are arranged in alphabetical order.

See
{url-dotfiles}[`dotfiles`],
{url-gento}[`gento`],
{url-pulse}[`pulse`], and
{url-toolbox}[`toolbox`]
as examples of projects that utilize this framework.

== Install

The artifact is a single non-executable POSIX-compliant shell script file
{url-base}[`base.sh`].
Install the file from the repository:

[,sh]
----
git clone git@github.com:rdavid/shellbase.git &&
  ./shellbase/app/install
----

Install the file from the released version.
Some operating systems demands administrative rights to install to
`/usr/local/bin`, use `sudo` or `doas` before `tar`:

[,sh]
----
REL=0.9.20250808
SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v$REL.tar.gz
curl --location --silent $SRC |
  tar \
    --directory /usr/local/bin \
    --extract \
    --gzip \
    --strip-components=2 \
    shellbase-$REL/lib/base.sh
----

== Using

Verify `/usr/local/bin` is in your `PATH`.
Then your script can use `shellbase`:

[,sh]
----
#!/bin/sh
# shellcheck disable=SC1091 # File not following.
. base.sh
log I\'m using the shellbase.
----

You can try `shellbase` without installation:

[,sh]
----
#!/bin/sh
REL=0.9.20250808
SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v$REL.tar.gz
eval "$(
  curl --location --silent $SRC |
    tar \
      --extract \
      --gzip \
      --to-stdout \
      shellbase-$REL/lib/base.sh
)"
log I\'m using the shellbase.
----

{url-base}#L572[`prettytable`] example:

[,sh]
----
. base.sh
{
  printf 'ID\tNAME\tTITLE\n'
  printf '123456789\tJohn Foo\tDirector\n'
  printf '12\tMike Bar\tEngineer\n'
} | prettytable
----

Output:

[,sh]
----
+-----------+----------+----------+
|ID         |NAME      |TITLE     |
+-----------+----------+----------+
|123456789  |John Foo  |Director  |
|12         |Mike Bar  |Engineer  |
+-----------+----------+----------+
----

== Test

The project uses Daniel J. Bernstein's build system {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.
`redo lint` applies the following linters to the source files:
{url-actionlint}[`actionlint`],
{url-checkmake}[`checkmake`],
{url-hadolint}[`hadolint`],
{url-reuse}[`reuse`],
{url-shellcheck}[`shellcheck`],
{url-shfmt}[`shfmt`],
{url-typos}[`typos`],
{url-vale}[`vale`],
{url-yamllint}[`yamllint`].
`redo test` runs unit tests in installed shells.
`redo test-container` runs the tests across various shells in containers.
It uses {url-cv}[David Rabkin]'s {url-goredoer}[`goredoer`] to build
{url-goredo}[`goredo`].

== Links

- {url-sh0}[Bash Pitfalls]
- {url-sh1}[Rich’s sh (POSIX shell) tricks]
- {url-sh2}[Sending and Trapping Signals]
- {url-sh3}[Sh - the POSIX Shell]

== License

`shellbase` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].
