// Settings:
:toc: macro
:!toc-title:
// URLs:
:url-base: https://github.com/rdavid/shellbase/blob/master/lib/base.sh
:url-checkmake: https://github.com/mrtazz/checkmake
:url-cv: http://cv.rabkin.co.il
:url-dotfiles: https://github.com/rdavid/dotfiles
:url-hadolint: https://github.com/hadolint/hadolint
:url-license: https://github.com/rdavid/shellbase/blob/master/LICENSE
:url-gento: https://github.com/rdavid/gento
:url-goredo: http://www.goredo.cypherpunks.ru/Install.html
:url-goredoer: https://github.com/rdavid/goredoer
:url-redo: http://cr.yp.to/redo.html
:url-sh0: http://www.etalabs.net/sh_tricks.html
:url-sh1: https://mywiki.wooledge.org/SignalTrap
:url-sh2: https://www.grymoire.com/Unix/Sh.html
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shfmt: https://github.com/mvdan/sh
:url-toolbox: https://github.com/rdavid/toolbox
:url-typos: https://github.com/crate-ci/typos
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint

= Shellbase

[,sh]
----
             ,,                 ,,    ,,  ,,                                  
           `7MM               `7MM  `7MM *MM                                  
             MM                 MM    MM  MM                                  
    ,pP"Ybd  MMpMMMb.  .gP"Ya   MM    MM  MM,dMMb.   ,6"Yb.  ,pP"Ybd  .gP"Ya  
    8I   `"  MM    MM ,M'   Yb  MM    MM  MM    `Mb 8)   MM  8I   `" ,M'   Yb 
    `YMMMa.  MM    MM 8M""""""  MM    MM  MM     M8  ,pm9MM  `YMMMa. 8M"""""" 
    L.   I8  MM    MM YM.    ,  MM    MM  MM.   ,M9 8M   MM  L.   I8 YM.    , 
    M9mmmP'.JMML  JMML.`Mbmmd'.JMML..JMML.P^YbmdP'  `Moo9^Yo.M9mmmP'  `Mbmmd' 
----

image:https://github.com/rdavid/shellbase/actions/workflows/test.yml/badge.svg[test,link=https://github.com/rdavid/shellbase/actions/workflows/test.yml]
image:https://hitsofcode.com/github/rdavid/shellbase?branch=master&label=hits%20of%20code[hits of code,link=https://hitsofcode.com/view/github/rdavid/shellbase?branch=master]
image:https://img.shields.io/github/v/release/rdavid/shellbase?color=blue&label=%20&logo=semver&logoColor=white&style=flat[release),link=https://github.com/rdavid/shellbase/releases]
image:https://img.shields.io/github/license/rdavid/shellbase?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat[license,link=https://github.com/rdavid/shellbase/blob/master/LICENSE]

toc::[]

== About

The `shellbase` framework serves as a foundation for Unix shell scripts.
This framework is mostly POSIX-compliant,
`Portable Operating System Interface for uniX`, ensuring compatibility across
Unix-like systems.
It offers a range of essential services, including public functions such as
logger and multiple validations, signal handling, garbage collection, and
support for multiple instances.

The `shellbase` defines global variables and functions.
All functions without `base_` prefix are public and could be used by clients.
The public functions are, in alphabetical order:
{url-base}#L61[`aud_only`],
{url-base}#L105[`beroot`],
{url-base}#L110[`beuser`],
{url-base}#L121[`bomb`],
{url-base}#L127[`cheat`],
{url-base}#L135[`cmd_exists`],
{url-base}#L148[`chrono_get`],
{url-base}#L189[`chrono_sta`],
{url-base}#L200[`chrono_sto`],
{url-base}#L210[`cya`],
{url-base}#L220[`die`],
{url-base}#L231[`echo`],
{url-base}#L250[`file_exists`],
{url-base}#L258[`grbt`],
{url-base}#L270[`handle_pipefails`],
{url-base}#L276[`heic2jpg`],
{url-base}#L300[`inside`],
{url-base}#L307[`isempty`],
{url-base}#L331[`isfunc`],
{url-base}#L344[`isnumber`],
{url-base}#L352[`isreadable`],
{url-base}#L361[`issolid`],
{url-base}#L395[`iswritable`],
{url-base}#L409[`log`],
{url-base}#L418[`loge`],
{url-base}#L426[`logw`],
{url-base}#L435[`map_del`],
{url-base}#L455[`map_get`],
{url-base}#L477[`map_put`],
{url-base}#L489[`pdf2jpg`],
{url-base}#L499[`pdf2png`],
{url-base}#L523[`prettytable`],
{url-base}#L549[`prettyuptime`],
{url-base}#L572[`realdir`],
{url-base}#L581[`realpath`],
{url-base}#L594[`semver`],
{url-base}#L612[`should_continue`],
{url-base}#L668[`timestamp`],
{url-base}#L688[`tolog`],
{url-base}#L694[`tologe`],
{url-base}#L701[`tolower`],
{url-base}#L719[`totsout`],
{url-base}#L725[`tsout`],
{url-base}#L733[`url_exists`],
{url-base}#L757[`user_exists`],
{url-base}#L773[`validate_cmd`],
{url-base}#L780[`validate_var`],
{url-base}#L787[`var_exists`],
{url-base}#L809[`ver_ge`],
{url-base}#L817[`vid2aud`],
{url-base}#L833[`yes_to_continue`],
{url-base}#L840[`ytda`].

Global variables have `BASE_` prefix and clients could use them.
Clients should place temporary files under `$BASE_WIP`.
All functions started with `base_` prefix are internal and should not be used
by clients.
The names are arranged in alphabetical order.

See {url-dotfiles}[`dotfiles`], {url-gento}[`gento`], and
{url-toolbox}[`toolbox`] as examples of projects that utilize this
framework.

== Install

The artifact is a single non-executable POSIX-compliant shell script file
{url-base}[`base.sh`].
Install the file from the repository:

[,sh]
----
git clone git@github.com:rdavid/shellbase.git &&
  ./shellbase/app/install
----

Install the file from the released version.
Some operating systems demands administrative rights to install to
`/usr/local/bin`, use `sudo` or `doas` before `tar`:

[,sh]
----
REL=0.9.20240707
SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v$REL.tar.gz
curl --location --silent $SRC |
  tar \
    --directory /usr/local/bin \
    --extract \
    --gzip \
    --strip-components=2 \
    shellbase-$REL/lib/base.sh
----

Verify `/usr/local/bin` is in your `PATH`.
Then your script can use `shellbase`:

[,sh]
----
#!/bin/sh
# shellcheck disable=SC1091 # File not following.
. base.sh
log I\'m using the shellbase.
----

You can try `shellbase` without installation:

[,sh]
----
#!/bin/sh
REL=0.9.20240707
SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v$REL.tar.gz
eval "$(
  curl --location --silent $SRC |
    tar \
      --extract \
      --gzip \
      --to-stdout \
      shellbase-$REL/lib/base.sh
)"
log I\'m using the shellbase.
----

{url-base}#L523[`prettytable`] example:

[,sh]
----
. base.sh
{
  printf 'ID\tNAME\tTITLE\n'
  printf '123456789\tJohn Foo\tDirector\n'
  printf '12\tMike Bar\tEngineer\n'
} | prettytable
----

Output:

[,sh]
----
+-----------+----------+----------+
|ID         |NAME      |TITLE     |
+-----------+----------+----------+
|123456789  |John Foo  |Director  |
|12         |Mike Bar  |Engineer  |
+-----------+----------+----------+
----

== Test

The project uses Daniel J. Bernstein's build system {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.
`redo lint` applies the following linters to the source files:
{url-checkmake}[`checkmake`], {url-hadolint}[`hadolint`],
{url-shellcheck}[`shellcheck`], {url-shfmt}[`shfmt`], {url-typos}[`typos`],
{url-vale}[`vale`], {url-yamllint}[`yamllint`].
`redo test` runs unit tests in installed shells.
`redo test-container` runs the tests across various shells in containers.
It uses {url-cv}[David Rabkin]'s {url-goredoer}[`goredoer`] to build
{url-goredo}[`goredo`].

== Links

- {url-sh0}[Rich’s sh (POSIX shell) tricks]
- {url-sh1}[Sending and Trapping Signals]
- {url-sh2}[Sh - the POSIX Shell]

== License

`shellbase` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].
