// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-hoc: https://hitsofcode.com/github/rdavid/shellbase?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/shellbase?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-releases: https://img.shields.io/github/v/release/rdavid/shellbase?color=blue&label=%20&logo=semver&logoColor=white&style=flat
:img-test-bsd: https://github.com/rdavid/shellbase/actions/workflows/test-bsd.yml/badge.svg
:img-test-lnx: https://github.com/rdavid/shellbase/actions/workflows/test-lnx.yml/badge.svg
:img-test-mac: https://github.com/rdavid/shellbase/actions/workflows/test-mac.yml/badge.svg
:url-actionlint: https://github.com/rhysd/actionlint
:url-base: https://github.com/rdavid/shellbase/blob/master/lib/base.sh
:url-checkmake: https://github.com/mrtazz/checkmake
:url-cv: http://cv.rabkin.co.il
:url-dotfiles: https://github.com/rdavid/dotfiles
:url-gento: https://github.com/rdavid/gento
:url-goredo: http://www.goredo.stargrave.org/INSTALL.html
:url-goredoer: https://github.com/rdavid/goredoer
:url-hadolint: https://github.com/hadolint/hadolint
:url-hoc: https://hitsofcode.com/view/github/rdavid/shellbase?branch=master
:url-license: https://github.com/rdavid/shellbase/blob/master/LICENSES/0BSD.txt
:url-pulse: https://github.com/rdavid/pulse
:url-redo: http://cr.yp.to/redo.html
:url-releases: https://github.com/rdavid/shellbase/releases
:url-reuse: https://github.com/fsfe/reuse-action
:url-sh0: https://mywiki.wooledge.org/BashPitfalls
:url-sh1: http://www.etalabs.net/sh_tricks.html
:url-sh2: https://mywiki.wooledge.org/SignalTrap
:url-sh3: https://www.grymoire.com/Unix/Sh.html
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shfmt: https://github.com/mvdan/sh
:url-test-bsd: https://github.com/rdavid/shellbase/actions/workflows/test-bsd.yml
:url-test-lnx: https://github.com/rdavid/shellbase/actions/workflows/test-lnx.yml
:url-test-mac: https://github.com/rdavid/shellbase/actions/workflows/test-mac.yml
:url-toolbox: https://github.com/rdavid/toolbox
:url-typos: https://github.com/crate-ci/typos
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint
:url-zizmor: https://github.com/zizmorcore/zizmor

= Shellbase

// The width is set to 79 characters, and the height is 8 lines. An ASCII art
// generator is used with the specific font Georgia 11 by Richard Sabey
// <cryptic_fan@hotmail.com> 9.2003:
//  http://patorjk.com/software/taag/#p=display&f=Georgia11&t=shellbase
[,sh]
----
              ,,                 ,,    ,,  ,,                                  
            `7MM               `7MM  `7MM *MM                                  
              MM                 MM    MM  MM                                  
     ,pP"Ybd  MMpMMMb.  .gP"Ya   MM    MM  MM,dMMb.   ,6"Yb.  ,pP"Ybd  .gP"Ya  
     8I   `"  MM    MM ,M'   Yb  MM    MM  MM    `Mb 8)   MM  8I   `" ,M'   Yb 
     `YMMMa.  MM    MM 8M""""""  MM    MM  MM     M8  ,pm9MM  `YMMMa. 8M"""""" 
     L.   I8  MM    MM YM.    ,  MM    MM  MM.   ,M9 8M   MM  L.   I8 YM.    , 
     M9mmmP'.JMML  JMML.`Mbmmd'.JMML..JMML.P^YbmdP'  `Moo9^Yo.M9mmmP'  `Mbmmd' 
----

image:{img-test-bsd}[text bsd,link={url-test-bsd}]
image:{img-test-lnx}[text lnx,link={url-test-lnx}]
image:{img-test-mac}[test mac,link={url-test-mac}]
image:{img-hoc}[hits of code,link={url-hoc}]
image:{img-releases}[release,link={url-releases}]
image:{img-license}[license,link={url-license}]

toc::[]

ifdef::pages-build[]
++++
<div id="repo-link">
  <a href="https://github.com/rdavid/shellbase" aria-label="GitHub repository" target="_blank" rel="noopener">
    <svg viewBox="0 0 16 16" width="18" height="18" fill="currentColor" aria-hidden="true">
      <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z"/>
    </svg>
  </a>
</div>
++++
endif::[]

== About

The `shellbase` framework serves as a foundation for Unix shell scripts.
It follows POSIX, the Portable Operating System Interface standard, and runs
on any Unix-like system.
The framework provides logging, validation helpers, signal handling, garbage
collection, and support for concurrent instances.

`shellbase` defines global variables and functions.
Clients may call any function without the `base_` prefix.
The public functions are, in alphabetical order:
{url-base}#L59[`aud_only`],
{url-base}#L98[`beroot`],
{url-base}#L105[`beuser`],
{url-base}#L119[`bomb`],
{url-base}#L125[`cheat`],
{url-base}#L136[`chrono_get`],
{url-base}#L181[`chrono_sta`],
{url-base}#L198[`chrono_sto`],
{url-base}#L219[`cmd_exists`],
{url-base}#L256[`cmd_run`],
{url-base}#L290[`cmd_runif`],
{url-base}#L299[`cya`],
{url-base}#L309[`die`],
{url-base}#L317[`dng2jpg`],
{url-base}#L326[`echo`],
{url-base}#L346[`ellipsize`],
{url-base}#L379[`file_exists`],
{url-base}#L395[`gitfix`],
{url-base}#L411[`gitlog`],
{url-base}#L437[`grbt`],
{url-base}#L455[`handle_pipefails`],
{url-base}#L466[`heic2jpg`],
{url-base}#L479[`inside`],
{url-base}#L491[`isempty`],
{url-base}#L520[`isfunc`],
{url-base}#L537[`isnumber`],
{url-base}#L549[`isreadable`],
{url-base}#L562[`isroot`],
{url-base}#L575[`issolid`],
{url-base}#L613[`iswritable`],
{url-base}#L630[`log`],
{url-base}#L639[`loge`],
{url-base}#L647[`logw`],
{url-base}#L656[`map_del`],
{url-base}#L680[`map_get`],
{url-base}#L706[`map_put`],
{url-base}#L727[`nmea2gpx`],
{url-base}#L741[`pdf2jpg`],
{url-base}#L746[`pdf2png`],
{url-base}#L768[`prettytable`],
{url-base}#L789[`prettyuptime`],
{url-base}#L813[`realdir`],
{url-base}#L827[`realpath`],
{url-base}#L845[`retry`],
{url-base}#L883[`rev`],
{url-base}#L901[`semver`],
{url-base}#L930[`should_continue`],
{url-base}#L988[`timestamp`],
{url-base}#L1008[`tolog`],
{url-base}#L1014[`tologe`],
{url-base}#L1021[`tolower`],
{url-base}#L1039[`totsout`],
{url-base}#L1045[`tsout`],
{url-base}#L1054[`url_exists`],
{url-base}#L1083[`user_exists`],
{url-base}#L1102[`validate_cmd`],
{url-base}#L1109[`validate_var`],
{url-base}#L1127[`var_exists`],
{url-base}#L1167[`ver_ge`],
{url-base}#L1182[`vid2aud`],
{url-base}#L1203[`ytda`].

Global variables carry the `BASE_` prefix.
Clients may use them and should place temporary files under `$BASE_WIP`.
Functions with the `base_` prefix stay internal.
Clients shouldn't call them.

See
{url-dotfiles}[`dotfiles`],
{url-gento}[`gento`],
{url-pulse}[`pulse`], and
{url-toolbox}[`toolbox`]
for example projects built on the framework.

== Install

The framework ships as a single non-executable POSIX shell script,
{url-base}[`base.sh`].
Install the file from the repository:

[,sh]
----
git clone https://github.com/rdavid/shellbase.git &&
  ./shellbase/app/install
----

Or install the file from a release.
Some operating systems demand administrative rights to write to
`/usr/local/bin`.
Prefix `tar` with `sudo` or `doas` when needed:

[,sh]
----
REL=0.9.20260707
SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v$REL.tar.gz
curl --location --silent $SRC |
  tar \
    --directory /usr/local/bin \
    --extract \
    --gzip \
    --strip-components=2 \
    shellbase-$REL/lib/base.sh
----

== Using

Verify `/usr/local/bin` appears in your `PATH`.
Then source the framework from your script:

[,sh]
----
#!/bin/sh
# File not following:
#  shellcheck disable=SC1091
. base.sh
log I\'m using the shellbase.
----

The framework provides three loggers:
{url-base}#L630[`log`] for information,
{url-base}#L639[`loge`] for errors, and
{url-base}#L647[`logw`] for warnings.
Each logger prints to standard error.
In non-interactive mode, each also appends the message to the log file under
a single lowercase level tag: `i` for information, `e` for errors, and `w`
for warnings.

Try `shellbase` without installation:

[,sh]
----
#!/bin/sh
REL=0.9.20260707
SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v$REL.tar.gz
eval "$(
  curl --location --silent $SRC |
    tar \
      --extract \
      --gzip \
      --to-stdout \
      shellbase-$REL/lib/base.sh
)"
log I\'m using the shellbase.
----

{url-base}#L768[`prettytable`] example:

[,sh]
----
. base.sh
{
  printf 'ID\tNAME\tTITLE\n'
  printf '123456789\tJohn Foo\tDirector\n'
  printf '12\tMike Bar\tEngineer\n'
} | prettytable
----

Output:

[,sh]
----
+-----------+----------+----------+
|ID         |NAME      |TITLE     |
+-----------+----------+----------+
|123456789  |John Foo  |Director  |
|12         |Mike Bar  |Engineer  |
+-----------+----------+----------+
----

== Test

The project uses Daniel J. Bernstein's build system, {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.
`redo lint` applies the following linters to the source files:
{url-actionlint}[`actionlint`],
{url-checkmake}[`checkmake`],
{url-hadolint}[`hadolint`],
{url-reuse}[`reuse`],
{url-shellcheck}[`shellcheck`],
{url-shfmt}[`shfmt`],
{url-typos}[`typos`],
{url-vale}[`vale`],
{url-yamllint}[`yamllint`],
{url-zizmor}[`zizmor`].
`redo test` runs the unit tests against each installed shell.
`redo test-container` repeats the tests inside the supported container
images.
The project uses {url-cv}[David Rabkin]'s {url-goredoer}[`goredoer`] to build
{url-goredo}[`goredo`].

A run of `redo lint` shows the conventions in practice: commands echo
before they run, missing linters stay silent instead of warning, a failure
doesn't stop the rest, and the script's only line of stdout is the bare
`OK` that redo reads as the target.

ifdef::pages-build[]
++++
<div id="term-demo">
  <div class="window">
    <div class="titlebar">
      <div class="dots">
        <span class="dot red"></span>
        <span class="dot yellow"></span>
        <span class="dot green"></span>
      </div>
      <span class="tab">lint.do &mdash; redo lint</span>
    </div>
    <div class="term-body">
      <div class="row">
        <span class="gutter"><span class="badge">1</span></span>
        <span class="prompt"><span class="sym">$</span> redo lint</span>
      </div>
      <div class="row">
        <span class="gutter"><span class="badge">2</span></span>
        <span class="info"><span class="ts">20260727-14:02:01</span> &raquo; dash -n ./lint.do</span>
      </div>
      <div class="row">
        <span class="gutter"></span>
        <span class="info"><span class="ts">20260727-14:02:01</span> &raquo; mksh -n ./lint.do</span>
      </div>
      <div class="row">
        <span class="gutter"></span>
        <span class="info"><span class="ts">20260727-14:02:02</span> &raquo; shellcheck ./*.do ./app/* ./lib/*</span>
      </div>
      <div class="row silence-row">
        <span class="gutter"><span class="badge">3</span></span>
        <span class="silence">actionlint, checkmake, hadolint &mdash; not installed, nothing logged</span>
      </div>
      <div class="row">
        <span class="gutter"><span class="badge">4</span></span>
        <span class="err"><span class="ts">20260727-14:02:04</span> shfmt failed, err=1.</span>
      </div>
      <div class="row">
        <span class="gutter"></span>
        <span class="info"><span class="ts">20260727-14:02:05</span> &raquo; yamllint ./.github/*.yml ./.github/workflows/*.yml</span>
      </div>
      <div class="row">
        <span class="gutter"><span class="badge">5</span></span>
        <span class="ok">OK</span>
      </div>
    </div>
  </div>
  <div class="legend">
    <h3>What the numbers point at</h3>
    <ol>
      <li>
        <span class="num">1</span>
        <p>No shellbase-specific CLI to learn &mdash; <code>redo lint</code> is a plain redo target running a POSIX <code>.do</code> script.</p>
      </li>
      <li>
        <span class="num">2</span>
        <p><code>cmd_run</code> echoes the exact command it's about to run, in the same green as every other info-level <code>log</code> line, before any output appears.</p>
      </li>
      <li>
        <span class="num">3</span>
        <p><code>cmd_runif</code> skips missing tools without a warning. Silence is the signal that a linter isn't installed, not a yellow line asking you to fix it.</p>
      </li>
      <li>
        <span class="num">4</span>
        <p>A genuine failure, printed in red by <code>loge</code>. One bad linter doesn't stop the rest &mdash; <code>lint.do</code> keeps going.</p>
      </li>
      <li>
        <span class="num">5</span>
        <p>The only line on stdout. redo reads it as the target's content; every line above it went to stderr.</p>
      </li>
    </ol>
  </div>
</div>
++++
endif::[]

ifndef::pages-build[]
[,sh]
----
$ redo lint
20260727-14:02:01 » dash -n ./lint.do
20260727-14:02:01 » mksh -n ./lint.do
20260727-14:02:02 » shellcheck ./*.do ./app/* ./lib/*
# actionlint, checkmake, hadolint - not installed, nothing logged
20260727-14:02:04 shfmt failed, err=1.
20260727-14:02:05 » yamllint ./.github/*.yml ./.github/workflows/*.yml
OK
----
endif::[]

== Links

- {url-sh0}[Bash Pitfalls]
- {url-sh1}[Rich’s sh (POSIX shell) tricks]
- {url-sh2}[Sending and Trapping Signals]
- {url-sh3}[Sh - the POSIX Shell]

== License

`shellbase` belongs to {url-cv}[David Rabkin] and uses a
{url-license}[Zero-Clause BSD license].

ifdef::pages-build[]
++++
<footer id="site-footer">
  <div class="footer-left">
    <img src="favicon.svg" alt="" width="20" height="20">
    <span>shellbase by <a href="http://cv.rabkin.co.il" target="_blank" rel="noopener">David Rabkin</a></span>
  </div>
  <div class="footer-links">
    <a href="https://github.com/rdavid/shellbase" target="_blank" rel="noopener">GitHub</a>
    <a href="https://github.com/rdavid/shellbase/releases" target="_blank" rel="noopener">Releases</a>
    <a href="https://github.com/rdavid/shellbase/blob/master/LICENSES/0BSD.txt" target="_blank" rel="noopener">0BSD License</a>
  </div>
</footer>
++++
endif::[]
