// Settings:
:toc: macro
:!toc-title:
// URLs:
:url-base: https://github.com/rdavid/shellbase/blob/master/lib/base.sh
:url-checkmake: https://github.com/mrtazz/checkmake
:url-cv: http://cv.rabkin.co.il
:url-dotfiles: https://github.com/rdavid/dotfiles
:url-hadolint: https://github.com/hadolint/hadolint
:url-license: https://github.com/rdavid/shellbase/blob/master/LICENSE
:url-gento: https://github.com/rdavid/gento
:url-goredo: http://www.goredo.cypherpunks.su/Install.html
:url-goredoer: https://github.com/rdavid/goredoer
:url-redo: http://cr.yp.to/redo.html
:url-sh0: https://mywiki.wooledge.org/BashPitfalls
:url-sh1: http://www.etalabs.net/sh_tricks.html
:url-sh2: https://mywiki.wooledge.org/SignalTrap
:url-sh3: https://www.grymoire.com/Unix/Sh.html
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shfmt: https://github.com/mvdan/sh
:url-toolbox: https://github.com/rdavid/toolbox
:url-typos: https://github.com/crate-ci/typos
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint

= Shellbase

[,sh]
----
             ,,                 ,,    ,,  ,,                                  
           `7MM               `7MM  `7MM *MM                                  
             MM                 MM    MM  MM                                  
    ,pP"Ybd  MMpMMMb.  .gP"Ya   MM    MM  MM,dMMb.   ,6"Yb.  ,pP"Ybd  .gP"Ya  
    8I   `"  MM    MM ,M'   Yb  MM    MM  MM    `Mb 8)   MM  8I   `" ,M'   Yb 
    `YMMMa.  MM    MM 8M""""""  MM    MM  MM     M8  ,pm9MM  `YMMMa. 8M"""""" 
    L.   I8  MM    MM YM.    ,  MM    MM  MM.   ,M9 8M   MM  L.   I8 YM.    , 
    M9mmmP'.JMML  JMML.`Mbmmd'.JMML..JMML.P^YbmdP'  `Moo9^Yo.M9mmmP'  `Mbmmd' 
----

image:https://github.com/rdavid/shellbase/actions/workflows/test.yml/badge.svg[test,link=https://github.com/rdavid/shellbase/actions/workflows/test.yml]
image:https://hitsofcode.com/github/rdavid/shellbase?branch=master&label=hits%20of%20code[hits of code,link=https://hitsofcode.com/view/github/rdavid/shellbase?branch=master]
image:https://img.shields.io/github/v/release/rdavid/shellbase?color=blue&label=%20&logo=semver&logoColor=white&style=flat[release),link=https://github.com/rdavid/shellbase/releases]
image:https://img.shields.io/github/license/rdavid/shellbase?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat[license,link=https://github.com/rdavid/shellbase/blob/master/LICENSE]

toc::[]

== About

The `shellbase` framework serves as a foundation for Unix shell scripts.
This framework is mostly POSIX-compliant,
`Portable Operating System Interface for uniX`, ensuring compatibility across
Unix-like systems.
It offers a range of essential services, including public functions such as
logger and multiple validations, signal handling, garbage collection, and
support for multiple instances.

The `shellbase` defines global variables and functions.
All functions without `base_` prefix are public and could be used by clients.
The public functions are, in alphabetical order:
{url-base}#L51[`aud_only`],
{url-base}#L95[`beroot`],
{url-base}#L100[`beuser`],
{url-base}#L111[`bomb`],
{url-base}#L117[`cheat`],
{url-base}#L125[`cmd_exists`],
{url-base}#L138[`chrono_get`],
{url-base}#L179[`chrono_sta`],
{url-base}#L190[`chrono_sto`],
{url-base}#L200[`cya`],
{url-base}#L210[`die`],
{url-base}#L221[`echo`],
{url-base}#L243[`ellipsize`],
{url-base}#L261[`file_exists`],
{url-base}#L269[`grbt`],
{url-base}#L281[`handle_pipefails`],
{url-base}#L287[`heic2jpg`],
{url-base}#L311[`inside`],
{url-base}#L318[`isempty`],
{url-base}#L342[`isfunc`],
{url-base}#L355[`isnumber`],
{url-base}#L363[`isreadable`],
{url-base}#L372[`issolid`],
{url-base}#L406[`iswritable`],
{url-base}#L420[`log`],
{url-base}#L429[`loge`],
{url-base}#L437[`logw`],
{url-base}#L446[`map_del`],
{url-base}#L466[`map_get`],
{url-base}#L488[`map_put`],
{url-base}#L500[`pdf2jpg`],
{url-base}#L510[`pdf2png`],
{url-base}#L534[`prettytable`],
{url-base}#L560[`prettyuptime`],
{url-base}#L583[`realdir`],
{url-base}#L592[`realpath`],
{url-base}#L605[`semver`],
{url-base}#L623[`should_continue`],
{url-base}#L679[`timestamp`],
{url-base}#L699[`tolog`],
{url-base}#L705[`tologe`],
{url-base}#L712[`tolower`],
{url-base}#L730[`totsout`],
{url-base}#L736[`tsout`],
{url-base}#L744[`url_exists`],
{url-base}#L768[`user_exists`],
{url-base}#L784[`validate_cmd`],
{url-base}#L791[`validate_var`],
{url-base}#L798[`var_exists`],
{url-base}#L820[`ver_ge`],
{url-base}#L828[`vid2aud`],
{url-base}#L842[`ytda`].

Global variables have `BASE_` prefix and clients could use them.
Clients should place temporary files under `$BASE_WIP`.
All functions started with `base_` prefix are internal and should not be used
by clients.
The names are arranged in alphabetical order.

See {url-dotfiles}[`dotfiles`], {url-gento}[`gento`], and
{url-toolbox}[`toolbox`] as examples of projects that utilize this
framework.

== Install

The artifact is a single non-executable POSIX-compliant shell script file
{url-base}[`base.sh`].
Install the file from the repository:

[,sh]
----
git clone git@github.com:rdavid/shellbase.git &&
  ./shellbase/app/install
----

Install the file from the released version.
Some operating systems demands administrative rights to install to
`/usr/local/bin`, use `sudo` or `doas` before `tar`:

[,sh]
----
REL=0.9.20250404
SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v$REL.tar.gz
curl --location --silent $SRC |
  tar \
    --directory /usr/local/bin \
    --extract \
    --gzip \
    --strip-components=2 \
    shellbase-$REL/lib/base.sh
----

== Using

Verify `/usr/local/bin` is in your `PATH`.
Then your script can use `shellbase`:

[,sh]
----
#!/bin/sh
# shellcheck disable=SC1091 # File not following.
. base.sh
log I\'m using the shellbase.
----

You can try `shellbase` without installation:

[,sh]
----
#!/bin/sh
REL=0.9.20250404
SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v$REL.tar.gz
eval "$(
  curl --location --silent $SRC |
    tar \
      --extract \
      --gzip \
      --to-stdout \
      shellbase-$REL/lib/base.sh
)"
log I\'m using the shellbase.
----

{url-base}#L534[`prettytable`] example:

[,sh]
----
. base.sh
{
  printf 'ID\tNAME\tTITLE\n'
  printf '123456789\tJohn Foo\tDirector\n'
  printf '12\tMike Bar\tEngineer\n'
} | prettytable
----

Output:

[,sh]
----
+-----------+----------+----------+
|ID         |NAME      |TITLE     |
+-----------+----------+----------+
|123456789  |John Foo  |Director  |
|12         |Mike Bar  |Engineer  |
+-----------+----------+----------+
----

== Test

The project uses Daniel J. Bernstein's build system {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.
`redo lint` applies the following linters to the source files:
{url-checkmake}[`checkmake`], {url-hadolint}[`hadolint`],
{url-shellcheck}[`shellcheck`], {url-shfmt}[`shfmt`], {url-typos}[`typos`],
{url-vale}[`vale`], {url-yamllint}[`yamllint`].
`redo test` runs unit tests in installed shells.
`redo test-container` runs the tests across various shells in containers.
It uses {url-cv}[David Rabkin]'s {url-goredoer}[`goredoer`] to build
{url-goredo}[`goredo`].

== Links

- {url-sh0}[Bash Pitfalls]
- {url-sh1}[Rich’s sh (POSIX shell) tricks]
- {url-sh2}[Sending and Trapping Signals]
- {url-sh3}[Sh - the POSIX Shell]

== License

`shellbase` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].
