// Settings:
:toc: macro
:!toc-title:
// URLs:
:url-base: https://github.com/rdavid/shellbase/blob/master/lib/base.sh
:url-checkmake: https://github.com/mrtazz/checkmake
:url-cv: http://cv.rabkin.co.il
:url-dotfiles: https://github.com/rdavid/dotfiles
:url-hadolint: https://github.com/hadolint/hadolint
:url-license: https://github.com/rdavid/shellbase/blob/master/LICENSE
:url-gento: https://github.com/rdavid/gento
:url-goredo: http://www.goredo.cypherpunks.ru/Install.html
:url-goredoer: https://github.com/rdavid/goredoer
:url-redo: http://cr.yp.to/redo.html
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shfmt: https://github.com/mvdan/sh
:url-toolbox: https://github.com/rdavid/toolbox
:url-typos: https://github.com/crate-ci/typos
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint

= Shellbase

image:https://github.com/rdavid/shellbase/actions/workflows/lint.yml/badge.svg[linters,link=https://github.com/rdavid/shellbase/actions/workflows/lint.yml]
image:https://hitsofcode.com/github/rdavid/shellbase?branch=master&label=hits%20of%20code[hits of code,link=https://hitsofcode.com/view/github/rdavid/shellbase?branch=master]
image:https://img.shields.io/github/downloads/rdavid/shellbase/total?color=blue&labelColor=gray&logo=singlestore&logoColor=lightgray&style=flat[downloads]
image:https://img.shields.io/github/v/release/rdavid/shellbase?color=blue&label=%20&logo=semver&logoColor=white&style=flat[release),link=https://github.com/rdavid/shellbase/releases]
image:https://img.shields.io/github/license/rdavid/shellbase?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat[license,link=https://github.com/rdavid/shellbase/blob/master/LICENSE]

toc::[]

== About

The `shellbase` framework serves as a foundation for Unix shell scripts.
This framework is mostly POSIX-compliant, ensuring compatibility across
Unix-like systems.
It offers a range of essential services, including public functions such as
logger and multiple validations, signal handling, garbage collection, and
support for multiple instances.

The `shellbase` defines global variables and functions.
All functions without `base_` prefix are public and could be used by clients.
The public functions are, in alphabetical order:
{url-base}#L54[`aud_only`],
{url-base}#L71[`beroot`],
{url-base}#L76[`beuser`],
{url-base}#L87[`bomb`],
{url-base}#L93[`cheat`],
{url-base}#L99[`cmd_exists`],
{url-base}#L115[`die`],
{url-base}#L124[`echo`],
{url-base}#L143[`file_exists`],
{url-base}#L158[`grbt`],
{url-base}#L168[`heic2jpg`],
{url-base}#L182[`inside`],
{url-base}#L190[`isempty`],
{url-base}#L204[`isfunc`],
{url-base}#L212[`isreadable`],
{url-base}#L228[`issolid`],
{url-base}#L257[`iswritable`],
{url-base}#L282[`log`],
{url-base}#L291[`loge`],
{url-base}#L299[`logw`],
{url-base}#L308[`pdf2jpg`],
{url-base}#L317[`pdf2png`],
{url-base}#L340[`prettytable`],
{url-base}#L365[`prettyuptime`],
{url-base}#L383[`realdir`],
{url-base}#L392[`realpath`],
{url-base}#L404[`semver`],
{url-base}#L421[`timestamp`],
{url-base}#L441[`tolog`],
{url-base}#L447[`tologe`],
{url-base}#L453[`tolower`],
{url-base}#L458[`totsout`],
{url-base}#L464[`tsout`],
{url-base}#L473[`url_exists`],
{url-base}#L498[`user_exists`],
{url-base}#L514[`validate_cmd`],
{url-base}#L521[`validate_var`],
{url-base}#L528[`var_exists`],
{url-base}#L549[`ver_ge`],
{url-base}#L554[`vid2aud`],
{url-base}#L569[`yes_to_continue`],
{url-base}#L623[`ytda`].

Global variables have `BASE_` prefix and clients could use them.
Clients should place temporary files under `$BASE_WIP`.
All functions started with `base_` prefix are internal and should not be used
by clients.
The names are arranged in alphabetical order.

See {url-dotfiles}[`dotfiles`], {url-gento}[`gento`], and
{url-toolbox}[`toolbox`] as examples of projects that utilize this
framework.

== Install

The artifact is a single non-executable POSIX-compliant shell script file
{url-base}[`base.sh`].
Install the file from the repository:

[,sh]
----
git clone git@github.com:rdavid/shellbase.git &&
  ./shellbase/app/install
----

Install the file from the released version.
Some operating systems demands administrative rights to install to
`/usr/local/bin`, use `sudo` or `doas` before `tar`:

[,sh]
----
REL=0.9.20230707
SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v$REL.tar.gz
curl --location --silent $SRC |
  tar \
    --directory /usr/local/bin \
    --extract \
    --gzip \
    --strip-components=2 \
    shellbase-$REL/lib/base.sh
----

Verify `/usr/local/bin` is in your `PATH`.
Then your script can use `shellbase`:

[,sh]
----
#!/bin/sh
# shellcheck disable=SC1091 # File not following.
. base.sh
log I\'m using the shellbase.
----

You can try `shellbase` without installation:

[,sh]
----
#!/bin/sh
REL=0.9.20230707
SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v$REL.tar.gz
eval "$(
  curl --location --silent $SRC |
    tar \
      --extract \
      --gzip \
      --to-stdout \
      shellbase-$REL/lib/base.sh
)"
log I\'m using the shellbase.
----

{url-base}#L329[`prettytable`] example:

[,sh]
----
. base.sh
{
  printf 'ID\tNAME\tTITLE\n'
  printf '123456789\tJohn Foo\tDirector\n'
  printf '12\tMike Bar\tEngineer\n'
} | prettytable
----

Output:

[,sh]
----
+-----------+----------+----------+
|ID         |NAME      |TITLE     |
+-----------+----------+----------+
|123456789  |John Foo  |Director  |
|12         |Mike Bar  |Engineer  |
+-----------+----------+----------+
----

== Test

The project uses Daniel J. Bernstein's build system {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.
`redo lint` applies the following linters to the source files:
{url-checkmake}[`checkmake`], {url-hadolint}[`hadolint`],
{url-shellcheck}[`shellcheck`], {url-shfmt}[`shfmt`], {url-typos}[`typos`],
{url-vale}[`vale`], {url-yamllint}[`yamllint`].
`redo test` runs unit tests in installed shells.
`redo test_container` runs the tests across various shells in containers.
It uses {url-cv}[David Rabkin]'s {url-goredoer}[`goredoer`] to build
{url-goredo}[`goredo`].

== License

`shellbase` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].
