// Settings:
:toc: macro
:!toc-title:
// URLs:
:url-base: https://github.com/rdavid/shellbase/blob/master/lib/base.sh
:url-dotfiles: https://github.com/rdavid/dotfiles
:url-cv: http://cv.rabkin.co.il
:url-license: https://github.com/rdavid/shellbase/blob/master/LICENSE
:url-gento: https://github.com/rdavid/gento
:url-goredo: http://www.goredo.cypherpunks.ru/Install.html
:url-goredoer: https://github.com/rdavid/goredoer
:url-redo: http://cr.yp.to/redo.html
:url-toolbox: https://github.com/rdavid/toolbox

= Shellbase

image:https://github.com/rdavid/shellbase/actions/workflows/lint.yml/badge.svg[linters,link=https://github.com/rdavid/shellbase/actions/workflows/lint.yml]
image:https://hitsofcode.com/github/rdavid/shellbase?branch=master&label=hits%20of%20code[hits of code,link=https://hitsofcode.com/view/github/rdavid/shellbase?branch=master]
image:https://img.shields.io/github/downloads/rdavid/shellbase/total?color=blue&labelColor=gray&logo=singlestore&logoColor=lightgray&style=flat[downloads]
image:https://img.shields.io/github/v/release/rdavid/shellbase?color=blue&label=%20&logo=semver&logoColor=white&style=flat[release),link=https://github.com/rdavid/shellbase/releases]
image:https://img.shields.io/github/license/rdavid/shellbase?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat[license,link=https://github.com/rdavid/shellbase/blob/master/LICENSE]

toc::[]

== About

The `shellbase` framework serves as a foundation for Unix shell scripts.
This framework is mostly POSIX-compliant, ensuring compatibility across
Unix-like systems.
It offers a range of essential services, including public functions such as
logger and multiple validations, signal handling, garbage collection, and
support for multiple instances.

The `shellbase` defines global variables and functions.
All functions without `base_` prefix are public and could be used by clients.
The public functions are, in alphabetical order:
{url-base}#L52[`aud_only`],
{url-base}#L69[`beroot`],
{url-base}#L74[`beuser`],
{url-base}#L85[`cheat`],
{url-base}#L91[`cmd_exists`],
{url-base}#L105[`die`],
{url-base}#L113[`echo`],
{url-base}#L131[`file_exists`],
{url-base}#L146[`grbt`],
{url-base}#L156[`heic2jpg`],
{url-base}#L170[`inside`],
{url-base}#L178[`isempty`],
{url-base}#L192[`isfunc`],
{url-base}#L200[`isreadable`],
{url-base}#L216[`issolid`],
{url-base}#L245[`iswritable`],
{url-base}#L269[`log`],
{url-base}#L279[`loge`],
{url-base}#L286[`logw`],
{url-base}#L296[`pdf2jpg`],
{url-base}#L305[`pdf2png`],
{url-base}#L328[`prettytable`],
{url-base}#L353[`prettyuptime`],
{url-base}#L371[`realdir`],
{url-base}#L380[`realpath`],
{url-base}#L392[`semver`],
{url-base}#L407[`timestamp`],
{url-base}#L427[`tolog`],
{url-base}#L433[`tologe`],
{url-base}#L439[`tolower`],
{url-base}#L444[`totsout`],
{url-base}#L450[`tsout`],
{url-base}#L469[`url_exists`],
{url-base}#L484[`user_exists`],
{url-base}#L500[`validate_cmd`],
{url-base}#L508[`validate_var`],
{url-base}#L514[`var_exists`],
{url-base}#L535[`ver_ge`],
{url-base}#L540[`vid2aud`],
{url-base}#L555[`yes_to_continue`],
{url-base}#L609[`ytda`].

Global variables have `BASE_` prefix and clients could use them.
Clients should place all temporarily files under `$BASE_WIP`.
All functions started with `base_` prefix are internal and should not be used
by clients.
All names are in alphabetical order.

See {url-dotfiles}[`dotfiles`], {url-gento}[`gento`] and {url-toolbox}[`toolbox`] as examples.

== Install

The artifact is a single non-executable POSIX-compliant shell script file
{url-base}[`base.sh`].
Install the file from the repository:

[,sh]
----
git clone git@github.com:rdavid/shellbase.git &&
  ./shellbase/app/install
----

Install the file from the released version.
Some operating systems demands administrative rights to install to
`/usr/local/bin`, use `sudo` or `doas` before `tar`:

[,sh]
----
REL=0.9.20230505
SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v$REL.tar.gz
curl --location --silent $SRC |
  tar \
    --directory /usr/local/bin \
    --extract \
    --gzip \
    --strip-components=2 \
    shellbase-$REL/lib/base.sh
----

Verify `/usr/local/bin` is in your `PATH`.
Then your script can use `shellbase`:

[,sh]
----
#!/bin/sh
# shellcheck disable=SC1091 # File not following.
. base.sh
log I\'m using the shellbase.
----

You can try `shellbase` without installation:

[,sh]
----
#!/bin/sh
REL=0.9.20230505
SRC=https://github.com/rdavid/shellbase/archive/refs/tags/v$REL.tar.gz
eval "$(
  curl --location --silent $SRC |
    tar \
      --extract \
      --gzip \
      --to-stdout \
      shellbase-$REL/lib/base.sh
)"
log I\'m using the shellbase.
----

{url-base}#L328[`prettytable`] example:

[,sh]
----
. base.sh
{
  printf 'ID\tNAME\tTITLE\n'
  printf '123456789\tJohn Foo\tDirector\n'
  printf '12\tMike Bar\tEngineer\n'
} | prettytable
----

Output:

[,sh]
----
+-----------+----------+----------+
|ID         |NAME      |TITLE     |
+-----------+----------+----------+
|123456789  |John Foo  |Director  |
|12         |Mike Bar  |Engineer  |
+-----------+----------+----------+
----

== Test

The project uses Daniel J. Bernstein's (aka, djb) build system
{url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.
`redo lint` runs the following linters on the source files:
https://github.com/mrtazz/checkmake[`checkmake`],
https://github.com/hadolint/hadolint[`hadolint`],
https://github.com/koalaman/shellcheck[`shellcheck`],
https://github.com/mvdan/sh[`shfmt`],
https://vale.sh[`vale`],
https://github.com/adrienverge/yamllint[`yamllint`].
`redo test` runs unit tests in installed shells.
`redo test_container` runs the tests in multiple shells in multiple containers.
It uses {url-cv}[David Rabkin]'s {url-goredoer}[`goredoer`] to build
{url-goredo}[`goredo`].

== License

`shellbase` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].
