FROM golang:1.19-alpine as builder
RUN \
	apk add --no-cache --update \
		zstd~=1.5 && \
	rm -rf /var/cache/apk/*
ENV \
	SHA=63cfdb24f14ec7071b5bb8ed237023410826ea9f21d48e8e6c9f43ae2af34176 \
	VER=1.27.0

# hadolint ignore=DL4006
RUN \
	wget --quiet \
		http://www.goredo.cypherpunks.ru/download/goredo-$VER.tar.zst && \
		printf '%s  %s' $SHA goredo-$VER.tar.zst | sha256sum -cs && \
	zstd --decompress < goredo-$VER.tar.zst | tar --extract --file -
WORKDIR /go/goredo-$VER/src
RUN go build -mod=vendor

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.6
LABEL maintainer="David Rabkin <david@rabkin.co.il>"
ENV \
	USER=shellbase
COPY LICENSE /licenses/LICENSE
WORKDIR /bin
COPY --from=builder /go/goredo-*/src/goredo .
RUN \
	microdnf update --assumeyes --disableplugin=subscription-manager && \
	rm --force --recursive /var/cache/yum && \
	microdnf install --assumeyes --disableplugin=subscription-manager \
		bash-4.4.20 \
		findutils-4.6.0 \
		shadow-utils-2:4.6-16.el8 \
	&& microdnf clean all --disableplugin=subscription-manager && \
	useradd --create-home "$USER" && \
	./goredo -symlinks
USER "$USER"
WORKDIR /home/"$USER"
COPY \
	--chown="$USER":"$USER" \
	. .
CMD \
	[ "redo", "-j=10", "-x", "test" ]
