# SPDX-FileCopyrightText: 2023-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
# hadolint global ignore=DL3041
FROM ghcr.io/rdavid/goredoer:0.9.20260707 as goredoer
FROM fedora:45
LABEL maintainer=David\ Rabkin\ <david@rabkin.co.il>
ENV \
	TIME_ZONE=Asia/Jerusalem \
	USER=shellbase
COPY LICENSES/* /licenses/
WORKDIR /bin
COPY --from=goredoer /goredo .
RUN \
	dnf update --assumeyes \
	&& rm --force --recursive /var/cache/yum \
	&& dnf install --assumeyes \
		bash \
		curl \
		diffutils \
		findutils \
		gawk \
		hadolint \
		oksh \
		perl-Digest-SHA \
		shadow-utils \
		shellcheck \
		procps \
		util-linux \
		yamllint \
		yash \
	&& dnf clean all \
	&& useradd --create-home "$USER" \
	&& cp /usr/share/zoneinfo/"$TIME_ZONE" /etc/localtime \
	&& printf %s "$TIME_ZONE" > /etc/timezone \
	&& goredo -symlinks
USER "$USER"
WORKDIR /home/"$USER"
COPY \
	--chown="$USER":"$USER" \
	. .
ENTRYPOINT [ "redo", "-j=10" ]
