#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# Copyright 2022-2023 David Rabkin
BSH="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
readonly \
	BSH \
	DST=/usr/local/bin \
	TGT=/usr/local/bin/base.sh

# shellcheck disable=SC1090 # File not following.
. "$BSH"
file_exists $DST || die $DST: No such directory.
iswritable $DST || die $DST is not writable.
file_exists $TGT &&
	yes_to_continue \
		"$(sh $TGT --quiet --version)" \
		is installed. Install \
		"$BASE_VERSION"?
cp -f "$BSH" $TGT || die Unable to copy "$BSH" to $TGT.
printf \
	'%s is installed to %s.\n' \
	"$(sh $TGT --quiet --version)" \
	$DST
