#!/bin/sh
# vi: lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2022-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# Verifies that file_exists succeeds for existing files, directories, and
# glob matches, and fails otherwise.
#
# File not following:
#  shellcheck disable=SC1090,SC1091
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
file_exists /tmp && log /tmp exists.
file_exists /tmp1 || log /tmp1 does not exist.
file_exists /tmp/* && log /tmp/\* exists.
file_exists /tmp1/* || log /tmp1/\* does not exist.
fle="$BASE_WIP/-dash-file"
touch "$fle" || die "$fle"
file_exists "$fle" && log "$fle" exists.
