#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# Copyright 2022-2023 David Rabkin
# shellcheck disable=SC1091 # File not following.
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
validate_cmd column
carbon=$(
	cat <<-EOM
		+-----------+----------+----------+
		|ID         |NAME      |TITLE     |
		+-----------+----------+----------+
		|123456789  |John Foo  |Director  |
		|12         |Mike Bar  |Engineer  |
		+-----------+----------+----------+
	EOM
)
out="$(
	{
		printf 'ID\tNAME\tTITLE\n'
		printf '123456789\tJohn Foo\tDirector\n'
		printf '12\tMike Bar\tEngineer\n'
	} |
		prettytable |
		awk '{print substr($0, index($0,$3))}'
)"
[ "$carbon" = "$out" ]
