#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# Copyright 2022 David Rabkin
# shellcheck disable=SC1091 # File not following.
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
i=0
while [ $i -ne 10 ]; do
	case "$((i%3))" in
		0) log "$i";;
		1) logw "$i";;
		2) loge "$i";;
	esac
	i="$((i+1))"
done
