#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2021-2025 David Rabkin
# SPDX-License-Identifier: 0BSD
# shellcheck disable=SC1090,SC1091 # File not following.
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
[ "$(id -u)" -eq 0 ] && die Skip run as root.
touch /tmp/1 /tmp/2
chmod -w /tmp/1
iswritable /tmp/1 /tmp/2 /tmp/3 && ret=0 || ret=1
chmod +w /tmp/1
rm /tmp/1 /tmp/2
exit "$ret"
