#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# Copyright 2022 David Rabkin
BASE="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh

# shellcheck disable=SC1090 # File not following.
. "$BASE"

# shellcheck disable=SC2034 # Appears unused.
BASE_APP_HASH=7ba1a25afff5fcd2466fd733426ced3d0756b1dbc84b2cbd1bd85577992eb658
is_solid
