#!/bin/sh
# vi: lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2023-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# Verifies that the --dir-wip option accepts a custom work-in-progress
# directory.
#
set -- --dir-wip .
BSH="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh

# File not following:
#  shellcheck disable=SC1090
. "$BSH"
