#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2022-2025 David Rabkin
# SPDX-License-Identifier: 0BSD
# shellcheck disable=SC1090,SC1091 # File not following.
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
var_exists \
	HOME \
	PATH \
	UNDEFINED_VAR1ABLE \
	USER
