#!/bin/sh
# vi: lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2023-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
# File not following:
#  shellcheck disable=SC1090,SC1091
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
isnumber 0 || die 0 is not a number.
isnumber 9 || die 9 is not a number.
isnumber 10 || die 10 is not a number.
isnumber 42 || die 42 is not a number.
