#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# Copyright 2022 David Rabkin
# shellcheck disable=SC1091
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
ver="$(semver 'I am 1.2.3')"
log "$ver"
inside "$ver" 0.0.0+nil && die
ver="$(semver 'I am 1.2.3+meta')"
log "$ver"
inside "$ver" 0.0.0+nil && die
ver="$(semver 'I am 1.2.3-4+alpha')"
log "$ver"
inside "$ver" 0.0.0+nil && die
ver="$(semver 'I am 1.2.3-4+beta')"
log "$ver"
inside "$ver" 0.0.0+nil && die
exit 0
