#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# Copyright 2023 David Rabkin
# shellcheck disable=SC2034 # Variable appears unused.
BASE_APP_USAGE="$(
	cat <<-EOM 2>&1
		  -b, --bar         Make bar.
		  -f, --foo         Make foo.

		Bar makes foo better. Use it respectfully.
	EOM
)" || {
	printf >&2 %s\\n "$BASE_APP_USAGE"
	exit 1
}
set -- --help

# shellcheck disable=SC1090,SC1091 # File not following.
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
