#!/bin/sh
# vi: lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2022-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# Verifies that user_exists fails when one of the given users does not
# exist.
#
# File not following:
#  shellcheck disable=SC1090
BSH="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
. "$BSH"
user_exists \
	nonexistentuser \
	root \
	"$USER"
