#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# Copyright 2021-2022 David Rabkin
# shellcheck disable=SC1091
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
i=1
while [ "$i" -ne 10 ]; do
	printf "%s\n" "$(base_duration 0)"
	i=$((i+1))
	sleep 1
done
