#!/bin/sh
# vi: lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2026 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# Verifies that iswritable handles a file name that collides with command
# options, such as -rf, instead of misparsing it as flags for touch or rm.
#
# File not following:
#  shellcheck disable=SC1090,SC1091
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
cd -- "$BASE_WIP" || die
iswritable -rf || die -rf is reported as not writable.
