#!/bin/sh
# vi: lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2022-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# Verifies that issolid succeeds when BASE_APP_HASH matches the running
# script's hash.
#
# File not following:
#  shellcheck disable=SC1090
BSH="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
. "$BSH"

# Appears unused:
#  shellcheck disable=SC2034
BASE_APP_HASH=711a18e5c7bdaa42db22f2ee619609c89553350c
issolid
