#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2021-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
# File not following:
#  shellcheck disable=SC1090,SC1091
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
isroot && die Skip run as root.
fle1="$BASE_WIP/1"
fle2="$BASE_WIP/2"
touch "$fle1" "$fle2"
chmod -w "$fle1"
iswritable "$fle1" "$fle2" "$BASE_WIP/3" && ret=0 || ret=1
chmod +w "$fle1"
rm "$fle1" "$fle2"
exit "$ret"
