#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
# File not following:
#  shellcheck disable=SC1090,SC1091
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
inp='Hello, world.'
out="$(ellipsize "$inp" 13)"
printf %s=%s\\n "$inp" "$out"
[ "$inp" = "$out" ]
out="$(ellipsize "$inp" 12)"
printf %s\\n "$out"
[ "$out" = 'Hello...rld.' ]
out="$(ellipsize "$inp" 4)"
printf %s\\n "$out"
[ "$out" = 'H...' ]
out="$(ellipsize "$inp" 3)"
printf %s\\n "$out"
[ "$out" = '...' ]
out="$(ellipsize "$inp" 2)"
printf %s\\n "$out"
[ "$out" = '...' ]
