#!/bin/sh
# vi: lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2026 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# Verifies that cmd_run succeeds for an existing command, with and without
# the quiet flag.
#
# File not following:
#  shellcheck disable=SC1090,SC1091
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
cmd_run : &&
	cmd_run -q : &&
	cmd_run printf ''
