#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# Copyright 2022 David Rabkin
BASE="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh

# shellcheck disable=SC1090
. "$BASE"

# shellcheck disable=SC2034
BASE_APP_HASH=6c98c7b786ef74a657c8b7418d1ded08905f746f3583814735912ef3c21db5ea
is_solid
exit 0
