#!/bin/sh
# vi: lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2022-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# Verifies that url_exists fails when any of the given URLs is unreachable.
#
# File not following:
#  shellcheck disable=SC1090
BSH="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
. "$BSH"
url_exists \
	file:///definitely-not-here \
	file:///etc/hosts
