#!/bin/sh
# vi: lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2026 David Rabkin
# SPDX-License-Identifier: 0BSD
# File not following:
#  shellcheck disable=SC1090,SC1091
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
cmd_runif : &&
	cmd_runif -q : &&
	cmd_runif printf '' &&
	cmd_runif c0mmand_n0t_f0und &&
	cmd_runif -q c0mmand_n0t_f0und
