#!/bin/sh
# vi: lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2022-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# Verifies that the deprecated validate_cmd fails when one of the given
# commands does not exist.
#
# File not following:
#  shellcheck disable=SC1090
BSH="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
. "$BSH"
validate_cmd \
	find \
	foobar_c0mmand \
	grep \
	ls
