#!/bin/sh
# vi: lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2022-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# Verifies that echo behaves consistently across the -n, -e, and -ne flags
# regardless of the shell's built-in echo.
#
# File not following:
#  shellcheck disable=SC1090,SC1091
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
echo hello

# Echo flags are undefined:
#  shellcheck disable=SC2039,SC3037
echo "-e"

# Echo won't expand escape sequences:
#  shellcheck disable=SC2028
echo "\\n"

# Echo flags are undefined:
#  shellcheck disable=SC2039,SC3037
echo -n hello

# Echo flags are undefined:
#  shellcheck disable=SC2039,SC3037
echo -ne hello
echo bye
