#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# Copyright 2022-2023 David Rabkin
# shellcheck disable=SC1090,SC1091 # File not following.
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
mkdir /tmp/empty-dir
isempty /tmp || log /tmp is not empty.
isempty /tmp/empty-dir && log /tmp/empty-dir is empty.
rmdir /tmp/empty-dir
