#!/bin/sh
# vi: lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2022-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
# File not following:
#  shellcheck disable=SC1090,SC1091
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
i=0
while [ "$i" -ne 10 ]; do
	case "$((i % 3))" in
	0) log "$i" ;;
	1) logw "$i" ;;
	2) loge "$i" ;;
	esac
	i="$((i + 1))"
done
