#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# Copyright 2021-2023 David Rabkin
# shellcheck disable=SC1090,SC1091 # File not following.
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
i=0
while [ "$i" -ne 3 ]; do
	log "$(base_duration 0)".
	i=$((i + 1))
	sleep 1
done
