#!/bin/sh
# vi: lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2026 David Rabkin
# SPDX-License-Identifier: 0BSD
# File not following:
#  shellcheck disable=SC1090,SC1091
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
fle="$BASE_WIP"/retry
out="$(
	retry sh -c "
		cnt=0
		[ -f \"\$1\" ] && cnt=\"\$(cat \"\$1\")\"
		cnt=\"\$((cnt + 1))\"
		printf %s \"\$cnt\" >\"\$1\"
		[ \"\$cnt\" -ge 3 ]
	" sh "$fle" 2>&1
)" || die "$out"
inside "$out" 'Retry 1/5:' || die "$out"
inside "$out" 'Retry 2 failed, err=1.' || die "$out"
inside "$out" 'Retry 3/5:' || die "$out"
[ "$(cat "$fle")" -eq 3 ] || die "$(cat "$fle")"
