#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2023-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
# File not following:
#  shellcheck disable=SC1090,SC1091
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
[ /usr = "$(realpath /usr)" ] || die 1
[ /usr = "$(realpath /usr/)" ] || die 2
[ /usr/local = "$(realpath /usr/local/)" ] || die 3
[ "$(basename -- "$0")" = "$(basename -- "$(realpath "$0")")" ] || die 4
