#!/bin/sh
# vi: lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2021-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# Verifies that iswritable succeeds for writable files and for paths that do
# not yet exist.
#
# File not following:
#  shellcheck disable=SC1090,SC1091
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
fle1="$BASE_WIP/1"
fle2="$BASE_WIP/2"
touch "$fle1" "$fle2"
iswritable "$fle1" "$fle2" "$BASE_WIP/3"
rm "$fle1" "$fle2"
