#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2023-2025 David Rabkin
# SPDX-License-Identifier: 0BSD
# shellcheck disable=SC1090,SC1091 # File not following.
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
ok=false
up="$(prettyuptime)"
for w in 0 1 2 3 4 5 6 7 8 9 day days hour hours less minute minutes; do
	inside "$up" $w && {
		log $w
		ok=true
	}
done
[ true = $ok ]
