#!/bin/sh
# vi: lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2023-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# Verifies that map_get fails for a key that was never put.
#
# File not following:
#  shellcheck disable=SC1090
BSH="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
. "$BSH"
map_put a key1 val1
map_get a key2
