#!/bin/sh
# vi: lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2023-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# Verifies that the --help flag prints the usage instructions, including an
# app-specific BASE_APP_USAGE addendum.
#
# Variable appears unused:
#  shellcheck disable=SC2034
BASE_APP_USAGE="$(
	cat <<-EOM 2>&1
		  -b, --bar         Make bar.
		  -f, --foo         Make foo.

		Bar makes foo better. Use it respectfully.
	EOM
)" || {
	printf >&2 %s\\n "$BASE_APP_USAGE"
	exit 1
}
set -- --help

# File not following:
#  shellcheck disable=SC1090,SC1091
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
