#!/bin/sh
# vi: lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2022-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# Verifies that isempty succeeds for an empty directory and fails for one
# with contents.
#
# File not following:
#  shellcheck disable=SC1090,SC1091
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
dir="$BASE_WIP/empty-dir"
mkdir "$dir"
isempty /tmp || log /tmp is not empty.
isempty "$dir" && log "$dir" is empty.
rmdir "$dir"
