#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# Copyright 2022-2023 David Rabkin
# shellcheck disable=SC2039,SC3043 # Uses local variables.
# shellcheck disable=SC1090,SC1091 # File not following.
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
foo() {
	local i=1
	while [ $i -le 3 ]; do
		echo ---
		echo a
		echo a >&2
		echo b
		echo b >&2
		echo c
		echo c >&2
		echo d
		echo d >&2
		i=$((i + 1))
		sleep 1
	done
}
{ foo 2>&1 1>&3 3>&- | tologe; } 3>&1 1>&2 | tolog
