#!/bin/sh
# vi: lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2026 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# Verifies that file_exists fails when any of the given files does not
# exist.
#
# File not following:
#  shellcheck disable=SC1090
BSH="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"/../lib/base.sh
. "$BSH"
file_exists \
	-q \
	/tmp \
	/tmp1 \
	/tmp2
