#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2023-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# Updates README.adoc with current links to the public functions. By default
# does not update the file and works as a linter.
#
# Uses local variables:
#  shellcheck disable=SC2039,SC3043
BSH="$(
	CDPATH='' cd -- "$(dirname -- "$0" 2>&1)" 2>&1 && pwd -P 2>&1
)"/../lib/base.sh || {
	err=$?
	printf >&2 %s\\n "$BSH"
	exit "$err"
}
BASE_APP_USAGE="$(
	cat <<-EOM 2>&1
		  -a, --action      Replaces README with updated version.
	EOM
)" || {
	err=$?
	printf >&2 %s\\n "$BASE_APP_USAGE"
	exit "$err"
}

# Variable appears unused:
#  shellcheck disable=SC2034
readonly \
	BASE_APP_USAGE \
	BASE_APP_VERSION=0.9.20260625 \
	BASE_MIN_VERSION=0.9.20231212 \
	BSH \
	TGT=README.adoc
set -- "$@" --quiet

# File not following:
#  shellcheck disable=SC1090
. "$BSH"
readonly \
	BEG="$BASE_WIP"/beg \
	END="$BASE_WIP"/end \
	MID="$BASE_WIP"/mid \
	OUT="$BASE_WIP"/out

# Parses arguments, validates the environment, analyzes the source, and updates.
main() {
	parse "$@"
	validate
	analyze
	update
}

# Parses base.sh for functions and re-creates new README. Uses GNU grep with
# PCRE option.
analyze() {
	local num
	num="$(awk '/The public functions are/ {print FNR}' "$TGT" 2>&1)" ||
		die "$num"
	head -n "$num" "$TGT" >"$BEG"
	grep --line-number --perl-regexp '^(?!base)\w.*{$' "$BSH" |
		rev |
		cut -c5- |
		rev |
		awk -F: '{print "{url-base}#L"$1"[`"$2"`],"}' |
		sed '$s/\,/./g' >"$MID"
	num="$(awk '/Global variables have/ {print FNR}' "$TGT" 2>&1)" ||
		die "$num"
	num=$((num - 1))
	tail -n +"$num" "$TGT" >"$END"
	cat "$BEG" "$MID" "$END" >"$OUT"
}

# Parses command line arguments.
parse() {
	local arg
	for arg; do
		shift
		case "$arg" in
		-a | --action) ACT=true ;;
		esac
	done
	var_exists ACT || ACT=false
	readonly ACT
}

# Compares the new README against the current one. Updates if needed.
update() {
	cmp --quiet "$OUT" "$TGT" && cya "$TGT" is updated.
	[ "$ACT" = false ] && die "$TGT" should be updated.
	iswritable "$TGT" || die
	cp -f "$OUT" "$TGT" || die Unable to update "$TGT".
	log "$TGT" has been updated.
}

# Checks the environment.
validate() {
	isreadable "$BSH" "$TGT" || die
	validate_cmd awk cat cmp cut grep head rev sed tail
	grep --help >/dev/null 2>&1 || {
		logw Stopped, GNU grep is required.
		cya
	}
}

# Entry point.
main "$@"
