# SPDX-FileCopyrightText: 2023-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
FROM ghcr.io/rdavid/goredoer:0.9.20260707 as goredoer
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.8-1784092902
LABEL maintainer=David\ Rabkin\ <david@rabkin.co.il>
ENV \
	TZ=Asia/Jerusalem \
	USER=shellbase
COPY LICENSES/* /licenses/
WORKDIR /bin
COPY --from=goredoer /goredo .
RUN \
	microdnf update --assumeyes --disableplugin=subscription-manager \
	&& rm --force --recursive /var/cache/yum \
	&& microdnf install --assumeyes --disableplugin=subscription-manager \
		bash-5.1.8 \
		diffutils-3.7 \
		findutils-4.8.0 \
		perl-Digest-SHA-6.02 \
		procps-ng-3.3.17 \
		tzdata-2026b \
		util-linux-2.37.4 \
	&& microdnf clean all --disableplugin=subscription-manager \
	&& useradd --create-home "$USER" \
	&& goredo -symlinks
USER "$USER"
WORKDIR /home/"$USER"
COPY \
	--chown="$USER":"$USER" \
	. .
ENTRYPOINT [ "redo", "-j=10" ]
