FROM ghcr.io/rdavid/goredoer:v0.9.20230113 AS goredoer
FROM debian:bullseye
LABEL maintainer=David\ Rabkin\ <david@rabkin.co.il>
ENV \
	DEBCONF_NOWARNINGS=yes \
	USER=shellbase
COPY LICENSE /licenses/LICENSE
WORKDIR /bin
COPY --from=goredoer /go/goredo-*/src/goredo .

# hadolint ignore=DL3008
RUN \
	apt-get update --assume-yes \
	&& apt-get upgrade --assume-yes \
	&& apt-get install --assume-yes --no-install-recommends \
		bash \
		curl \
		dash \
		fish \
		ksh \
		tcsh \
		zsh \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* \
	&& useradd --create-home "$USER" \
	&& ./goredo -symlinks
USER "$USER"
WORKDIR /home/"$USER"
COPY \
	--chown="$USER":"$USER" \
	. .
CMD \
	[ "redo", "-j=10", "-x", "test" ]
