# SPDX-FileCopyrightText: 2023-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
# hadolint global ignore=DL3008
FROM ghcr.io/rdavid/goredoer:0.9.20260707 as goredoer
FROM debian:trixie
LABEL maintainer=David\ Rabkin\ <david@rabkin.co.il>
ENV \
	DEBCONF_NOWARNINGS=yes \
	TIME_ZONE=Asia/Jerusalem \
	USER=shellbase
COPY LICENSES/* /licenses/
WORKDIR /bin
COPY --from=goredoer /goredo .
RUN \
	apt-get update --assume-yes \
	&& apt-get upgrade --assume-yes \
	&& apt-get install --assume-yes --no-install-recommends \
		bash \
		curl \
		dash \
		fish \
		ksh \
		libdigest-sha-perl \
		procps \
		shellcheck \
		tcsh \
		yamllint \
		zsh \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* \
	&& groupadd --gid 1001 "$USER" \
	&& useradd --create-home --gid 1001 --uid 1001 "$USER" \
	&& cp /usr/share/zoneinfo/"$TIME_ZONE" /etc/localtime \
	&& printf %s "$TIME_ZONE" > /etc/timezone \
	&& goredo -symlinks
USER "$USER"
WORKDIR /home/"$USER"
COPY \
	--chown="$USER":"$USER" \
	. .
ENTRYPOINT [ "redo", "-j=10" ]
