FROM alpine:3.15.4
LABEL maintainer="David Rabkin <david@rabkin.co.il>"
ENV \
	TIME_ZONE=Asia/Jerusalem \
	USER=shellbase
RUN \
	apk add --no-cache --update \
		curl=7.80.0-r1 \
		git=2.34.2-r0 \
		python3=3.9.7-r4 \
		tzdata=2022a-r0 && \
	addgroup -S "$USER" && \
	adduser -S "$USER" -G "$USER" && \
	printf '%s' "$TIME_ZONE" > /etc/timezone && \
	cp /usr/share/zoneinfo/"$TIME_ZONE" /etc/localtime && \
	rm -rf /var/cache/apk/*
RUN \
	git clone \
		--branch redo-0.42d \
		--config advice.detachedHead=false \
		--quiet \
		https://github.com/apenwarr/redo
WORKDIR /redo
RUN \
	DESTDIR='' PREFIX=/usr/local ./do --jobs=10 install >/dev/null 2>&1 && \
	./do --jobs=10 clean >/dev/null 2>&1
USER "$USER"
WORKDIR /home/"$USER"
COPY \
	--chown="$USER":"$USER" \
	. .
ENTRYPOINT \
	[ \
		"redo", \
		"--jobs=10", \
		"--verbose", \
		"--xtrace" \
	]
CMD \
	[ "test" ]
