FROM golang:1.19.3-alpine AS goredoer
LABEL maintainer=David\ Rabkin\ <david@rabkin.co.il>
RUN \
	apk add --no-cache --update \
		curl~=7.83.1 \
		zstd~=1.5.2 \
		&& rm -rf /var/cache/apk/*
ENV \
	SHA=9a5cdaa2c6fb1986b0d5d7ebfcd97122b0d7506fc30ca3da0578b04461d53c67 \
	VER=1.28.0
ENV \
	NME=goredo-$VER.tar.zst \
	URL=http://www.goredo.cypherpunks.ru/download/goredo-$VER.tar.zst

# Set the SHELL option -o pipefail before RUN with a pipe in.
# hadolint ignore=DL4006
RUN \
	curl --location --remote-name --silent $URL \
		&& printf %s\ \ %s $SHA $NME | sha256sum -cs \
		&& zstd --decompress < $NME | tar --extract --file -
WORKDIR /go/goredo-$VER/src
RUN go build -mod=vendor

FROM alpine:3.16.3
LABEL maintainer=David\ Rabkin\ <david@rabkin.co.il>
ENV \
	TIME_ZONE=Asia/Jerusalem \
	USER=shellbase
COPY LICENSE /licenses/LICENSE
WORKDIR /bin
COPY --from=goredoer /go/goredo-*/src/goredo .
RUN \
	apk add --no-cache --update \
		bash~=5.1 \
		curl~=7.83 \
		dash~=0.5 \
		fish~=3.4 \
		loksh~=7.1 \
		tcsh~=6.24 \
		tzdata~=2022 \
		zsh~=5.8 \
		util-linux~=2 \
		&& rm -rf /var/cache/apk/* \
		&& addgroup -S "$USER" \
		&& adduser -S "$USER" -G "$USER" \
		&& cp /usr/share/zoneinfo/$TIME_ZONE /etc/localtime \
		&& printf %s "$TIME_ZONE" > /etc/timezone \
		&& ./goredo -symlinks
USER "$USER"
WORKDIR /home/"$USER"
COPY \
	--chown="$USER":"$USER" \
	. .
CMD \
	[ "redo", "-j=10", "-x", "test" ]
