# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: actionlint
'on':
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
defaults:
  run:
    shell: sh
jobs:
  actionlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - id: get
        run: |
          srv=https://raw.githubusercontent.com/rhysd/actionlint
          ver=1.7.12
          curl --fail --location --silent --show-error \
            --output "$RUNNER_TEMP"/app \
            "$srv/v$ver/scripts/download-actionlint.bash"
          bash "$RUNNER_TEMP"/app "$ver"
      - env:
          exe: ${{ steps.get.outputs.executable }}
        run: "$exe"
