# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: actionlint
'on':
  push:
    branches: [master]
  pull_request:
permissions:
  contents: read
env:
  URL: https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash # yamllint disable-line
jobs:
  actionlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6.0.3
      - id: get
        run: curl --fail --location --silent --show-error "$URL" | bash
      - run: ${{ steps.get.outputs.executable }}
