---
name: linters
'on': push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Containerfile
          recursive: true
      - uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: ./*.md
      - uses: ludeeus/action-shellcheck@master
        with:
          additional_files: ./*.do app/* lib/*
      - uses: mfinelli/setup-shfmt@v2
      - run: shfmt -d *.do app/* lib/*
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/*.yml
          strict: true
