---
name: linters
'on': push
env:
  CM_BIN: /usr/local/bin/checkmake
  CM_URL: https://github.com/mrtazz/checkmake/releases/download/0.2.2/checkmake-0.2.2.linux.amd64 # yamllint disable-line
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl --location --output $CM_BIN --silent $CM_URL
          chmod +x $CM_BIN
          $CM_BIN Makefile
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Containerfile
          recursive: true
      - uses: ludeeus/action-shellcheck@master
        with:
          additional_files: ./*.do app/* lib/*
      - uses: mfinelli/setup-shfmt@v2
      - run: shfmt -d *.do app/* lib/*
      - uses: crate-ci/typos@master
      - uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
          files: README.adoc
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/*.yml .github/workflows/*.yml
          strict: true
      - run: ./app/update
