---
name: linters
'on': [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Containerfile
          recursive: true
      - uses: ludeeus/action-shellcheck@master
        with:
          additional_files: install lib/base.sh *.do
          scandir: app
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/*.yml
