# SPDX-FileCopyrightText: 2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: pages
'on':
  push:
    branches: [master]
    paths: [README.adoc, .github/pages/**]
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: pages
  cancel-in-progress: false
defaults:
  run:
    shell: sh
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes asciidoctor
      - run: |
          mkdir _site
          cp .github/pages/favicon.svg _site/favicon.svg
          asciidoctor \
            --attribute docinfo=private \
            --attribute docinfodir=.github/pages \
            --attribute pages-build \
            --out-file _site/index.html \
            README.adoc
      - uses: actions/configure-pages@v6.0.0
      - uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: _site
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5.0.0
