# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: reuse
'on':
  push:
    branches: [master]
  pull_request:
permissions:
  contents: read
jobs:
  reuse:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: fsfe/reuse-action@v6.0.0
