# SPDX-FileCopyrightText: 2025 David Rabkin
# SPDX-License-Identifier: 0BSD
---
'on': [pull_request, push]
name: shellcheck
jobs:
  shellcheck:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      - uses: ludeeus/action-shellcheck@master
        with:
          additional_files: ./*.do ./app/* ./lib/*
