# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: shellcheck
'on':
  pull_request:
  push:
    branches: [master]
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  shellcheck:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: ludeeus/action-shellcheck@2.0.0
        with:
          additional_files: ./*.do ./app/* ./lib/*
