# SPDX-FileCopyrightText: 2025 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: shfmt
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  shfmt:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: mfinelli/setup-shfmt@v3
      - run: shfmt -d ./*.do ./app/* ./lib/*
