---
name: test
'on': push
jobs:
  test-linux:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install asciidoctor
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Containerfile
          recursive: true
      - uses: ludeeus/action-shellcheck@master
        with:
          additional_files: ./*.do app/* lib/*
      - uses: mfinelli/setup-shfmt@v3
      - run: shfmt -d *.do app/* lib/*
      - uses: crate-ci/typos@master
      - uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
          files: README.adoc
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/*.yml .github/workflows/*.yml
          strict: true
      - run: ./app/update
  test-macos:
    strategy:
      matrix:
        os:
          - macos-13
          - macos-14
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          brew install \
            asciidoctor \
            checkmake \
            fish \
            goredo \
            grep \
            hadolint \
            shellcheck \
            shfmt \
            typos-cli \
            vale \
            yamllint \
            yash
          vale sync
          export PATH=/usr/local/opt/grep/libexec/gnubin:"$PATH"
          export PATH=/opt/homebrew/opt/grep/libexec/gnubin:"$PATH"
          redo -xx lint test
