# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: test-bsd
'on':
  pull_request:
    paths: &paths
      - '*.do'
      - app/**
      - lib/**
  push:
    branches: [master]
    paths: *paths
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
defaults:
  run:
    shell: sh
jobs:
  test-bsd:
    name: Test BSD on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - uses: vmactions/freebsd-vm@v1.4.8
        with:
          prepare: |
            pkg update
            pkg install -y \
              bash \
              curl \
              goredo \
              p5-Digest-SHA
            cd /usr/local/bin
            goredo -symlinks
            cd -
            ln -s /usr/local/bin/bash /bin/bash
          run: |
            redo -xx lint test
