# SPDX-FileCopyrightText: 2023-2025 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: test
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-13
          - macos-14
          - macos-15
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          brew install \
            fish \
            goredo \
            grep \
            yash
          export PATH=/opt/homebrew/opt/grep/libexec/gnubin:"$PATH"
          redo -xx test
