# SPDX-FileCopyrightText: 2023-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
# This workflow has limitations: Ubuntu lacks a redo package, and macOS
# cannot run containers natively.
---
name: test-mac
'on':
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
defaults:
  run:
    shell: sh
jobs:
  test-mac:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15
          - macos-15-intel
          - macos-26
          - macos-26-intel
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - run: |
          brew install \
            goredo \
            grep \
            yash
          gnubin="$(brew --prefix grep)/libexec/gnubin"
          export PATH="$gnubin:$PATH"
          redo -xx lint test
