# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: test-lnx
'on':
  pull_request:
  push:
    branches: [master]
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-lnx:
    name: Test ${{ matrix.img }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        img:
          - alpine
          - archlinux
          - debian
          - fedora
          - ubi8
          - ubi9
          - ubi10
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.0
      - run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes podman
      - uses: redhat-actions/buildah-build@v2.13
        with:
          containerfiles: ./container/${{ matrix.img }}/Containerfile
          image: ${{ matrix.img }}
          tags: latest
      - run: |
          podman run --rm ${{ matrix.img }}:latest lint test
