# SPDX-FileCopyrightText: 2023-2025 David Rabkin
# SPDX-License-Identifier: 0BSD
# This workflow has limitations -- Ubuntu lacks a redo package, and macOS
# cannot run containers natively.
---
name: test-mac
'on': [pull_request, push]
jobs:
  test-mac:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os:
          - macos-14
          - macos-15
          - macos-15-intel
    steps:
      - uses: actions/checkout@v5
      - run: |
          brew upgrade
          brew install \
            goredo \
            grep \
            yash
          export PATH=/opt/homebrew/opt/grep/libexec/gnubin:"$PATH"
          redo -xx lint test
