# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: typos
'on': [pull_request, push]
permissions:
  contents: read
jobs:
  typos:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: crate-ci/typos@v1.47.2
