# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: vale
'on':
  push:
    branches: [master]
  pull_request:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  vale:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6.0.3
      - run: sudo apt-get install asciidoctor
      - uses: vale-cli/vale-action@2.1.2
        with:
          fail_on_error: true
