FROM archlinux:base
LABEL maintainer=David\ Rabkin\ <david@rabkin.co.il>
ENV \
	USER=shellbase
COPY LICENSE /licenses/LICENSE
WORKDIR /bin
COPY --from=ghcr.io/rdavid/goredoer:v0.9.20230210 /go/goredo .

# Multiple redirections compete for stdout.
# hadolint ignore=SC2261
RUN \
	pacman-key --init >/dev/null 2>&1 \
	&& pacman --noconfirm --refresh --sync archlinux-keyring >/dev/null 2>&1 \
	&& pacman --noconfirm --refresh --sync --sysupgrade >/dev/null 2>&1 \
	&& pacman --noconfirm --sync \
		bash>=5.1 \
		dash>=0.5 \
		fish>=3.5 \
		ksh>=2020 \
		tcsh>=6.24 \
		zsh>=r5.9 \
	&& useradd --create-home "$USER" \
	&& goredo -symlinks
USER "$USER"
WORKDIR /home/"$USER"
COPY \
	--chown="$USER":"$USER" \
	. .
CMD \
	[ "redo", "-j=10", "-x", "test" ]
