FROM golang:1.19-alpine as builder
RUN \
	apk add --no-cache --update \
		zstd~=1.5 && \
	rm -rf /var/cache/apk/*
ENV \
	SHA=63cfdb24f14ec7071b5bb8ed237023410826ea9f21d48e8e6c9f43ae2af34176 \
	VER=1.27.0

# hadolint ignore=DL4006
RUN \
	wget --quiet \
		http://www.goredo.cypherpunks.ru/download/goredo-$VER.tar.zst && \
		printf '%s  %s' $SHA goredo-$VER.tar.zst | sha256sum -cs && \
	zstd --decompress < goredo-$VER.tar.zst | tar --extract --file -
WORKDIR /go/goredo-$VER/src
RUN go build -mod=vendor

FROM archlinux:base
LABEL maintainer="David Rabkin <david@rabkin.co.il>"
ENV \
	USER=shellbase
COPY LICENSE /licenses/LICENSE
WORKDIR /bin
COPY --from=builder /go/goredo-*/src/goredo .
RUN \
	pacman --noconfirm --refresh --sync --sysupgrade >/dev/null 2>&1 && \
	useradd --create-home "$USER" && \
	./goredo -symlinks
USER "$USER"
WORKDIR /home/"$USER"
COPY \
	--chown="$USER":"$USER" \
	. .
CMD \
	[ "redo", "-j=10", "-x", "test" ]
